import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, Database, Download, FolderOpen, LoaderCircle, LogIn, LogOut, MessageSquare, Play, RefreshCw, Save, Send, ShieldCheck, Sparkles, Square, Upload } from "lucide-react";
import { useOutletContext } from "react-router-dom";
import type { AiAnalysisSnapshot, AiAnalyzerMode, AiChatMessage, AiExportFormat, AiServiceKey, AiSettingsUpdate, ChatGptStatus } from "../../shared/aiAnalysisContract";
import type { AppOutletContext } from "../components/AppLayout";

type Tab = "diagnostics" | "workspace" | "results";
type Tone = "slate" | "green" | "amber" | "red" | "blue";

function Pill({ children, tone = "slate" }: { children: React.ReactNode; tone?: Tone }) {
  const colors = { slate: "bg-slate-100 text-slate-700", green: "bg-emerald-100 text-emerald-800", amber: "bg-amber-100 text-amber-900", red: "bg-red-100 text-red-800", blue: "bg-blue-100 text-blue-800" };
  return <span className={`inline-flex max-w-full items-center rounded px-2 py-1 text-[11px] font-black ${colors[tone]}`}>{children}</span>;
}

function Panel({ title, subtitle, children, actions }: { title: string; subtitle?: string; children: React.ReactNode; actions?: React.ReactNode }) {
  return <section className="min-w-0 rounded-md border border-line bg-white p-4 shadow-sm"><div className="mb-4 flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="text-base font-black text-ink">{title}</h2>{subtitle ? <p className="mt-1 break-words text-xs font-semibold leading-relaxed text-muted">{subtitle}</p> : null}</div>{actions}</div>{children}</section>;
}

function Field({ label, value, type = "text", onChange, placeholder }: { label: string; value: string; type?: string; onChange: (value: string) => void; placeholder?: string }) {
  return <label className="min-w-0 text-xs font-black text-slate-700"><span className="mb-1 block">{label}</span><input className="field w-full" type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>;
}

function runtimeTone(state: ChatGptStatus["state"]): Tone { return state === "connected" ? "green" : state === "usage_limited" || state === "login_pending" ? "amber" : state === "runtime_error" ? "red" : "slate"; }
function quotaText(value: ChatGptStatus["primaryRateLimit"]) { return value?.usedPercent === null || value?.usedPercent === undefined ? "Unavailable" : `${Math.round(value.usedPercent)}% used${value.resetsAt ? ` · resets ${new Date(value.resetsAt).toLocaleString("zh-TW")}` : ""}`; }

function ChatGptDiagnostics({ snapshot, setSnapshot, notice }: { snapshot: AiAnalysisSnapshot; setSnapshot: (value: AiAnalysisSnapshot) => void; notice: (value: string) => void }) {
  const api = window.desktopApp?.aiAnalysis;
  const status = snapshot.chatgpt;
  const [busy, setBusy] = useState(false);
  async function action(kind: "start" | "login" | "cancelLogin" | "logout" | "refresh") {
    if (!api) return; setBusy(true);
    const fn = kind === "start" ? api.startChatGpt : kind === "login" ? api.loginChatGpt : kind === "cancelLogin" ? api.cancelChatGptLogin : kind === "logout" ? api.logoutChatGpt : api.refreshChatGpt;
    const result: { ok: boolean; errorCode?: string; message?: string } = await fn(); setBusy(false);
    const latest = await api.getSnapshot(); setSnapshot(latest);
    notice(result.ok ? (kind === "login" ? "已在預設瀏覽器開啟 ChatGPT 安全登入。 / ChatGPT sign-in opened in your browser." : "ChatGPT 狀態已更新。 / ChatGPT status refreshed.") : `${result.errorCode ?? "CHATGPT_ERROR"}: ${result.message ?? "Operation failed."}`);
  }
  return <Panel title="ChatGPT via Codex App Server" subtitle="ChatGPT managed authentication stays inside the bundled Codex runtime. Jira Activity Analyzer never receives or stores OAuth tokens." actions={<Pill tone={runtimeTone(status.state)}>{status.state}</Pill>}>
    <div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <div className="rounded-md bg-slate-50 p-3"><span className="text-[10px] font-black text-muted">RUNTIME</span><b className="mt-1 block break-words text-sm">{status.runtimeFound ? `Codex ${status.runtimeVersion}` : "Not started"}</b></div>
      <div className="rounded-md bg-slate-50 p-3"><span className="text-[10px] font-black text-muted">ACCOUNT</span><b className="mt-1 block break-words text-sm">{status.accountEmailMasked ?? "Not signed in"}</b></div>
      <div className="rounded-md bg-slate-50 p-3"><span className="text-[10px] font-black text-muted">PLAN</span><b className="mt-1 block text-sm">{status.planType ?? "Unknown"}</b></div>
      <div className="rounded-md bg-slate-50 p-3"><span className="text-[10px] font-black text-muted">PRIMARY LIMIT</span><b className="mt-1 block break-words text-sm">{quotaText(status.primaryRateLimit)}</b></div>
    </div>
    <div className="mt-3 grid min-w-0 grid-cols-1 gap-3 md:grid-cols-[minmax(0,1fr)_auto]">
      <label className="min-w-0 text-xs font-black text-slate-700"><span className="mb-1 block">Model</span><select className="field w-full" disabled={status.state !== "connected"} value={status.selectedModel ?? ""} onChange={async (event) => { if (!api) return; await api.selectChatGptModel(event.target.value || null); setSnapshot(await api.getSnapshot()); }}><option value="">Auto</option>{status.models.map((model) => <option key={model.id} value={model.id}>{model.displayName}</option>)}</select></label>
      <div className="flex flex-wrap items-end gap-2"><button className="btn" disabled={busy} onClick={() => void action(status.state === "stopped" || status.state === "runtime_error" ? "start" : "refresh")}><RefreshCw className={busy ? "animate-spin" : ""} size={15} />Refresh</button>{status.state === "signed_out" ? <button className="btn btn-primary" disabled={busy} onClick={() => void action("login")}><LogIn size={15} />Sign in with ChatGPT</button> : null}{status.state === "login_pending" ? <button className="btn" disabled={busy} onClick={() => void action("cancelLogin")}><Square size={15} />Cancel login</button> : null}{status.authMode === "chatgpt" ? <button className="btn" disabled={busy} onClick={() => void action("logout")}><LogOut size={15} />Logout</button> : null}</div>
    </div>
    {status.lastErrorMessage ? <div className="mt-3 rounded-md border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-800">{status.lastErrorCode}: {status.lastErrorMessage}</div> : null}
    <div className="mt-3 flex items-start gap-2 rounded-md border border-blue-200 bg-blue-50 p-3 text-xs font-semibold leading-relaxed text-blue-900"><ShieldCheck className="mt-0.5 shrink-0" size={15} />Threads are ephemeral and read-only. Command, file, permission, MCP, plugin, skill, and dynamic tool requests are blocked automatically.</div>
  </Panel>;
}

function AiNexusSettings({ snapshot, setSnapshot, notice }: { snapshot: AiAnalysisSnapshot; setSnapshot: (value: AiAnalysisSnapshot) => void; notice: (value: string) => void }) {
  const source = snapshot.env.aiNexus;
  const [form, setForm] = useState(() => ({ ...source, secret: "" }));
  const [busy, setBusy] = useState(false);
  useEffect(() => setForm({ ...source, secret: "" }), [source.configFingerprint]);
  const update = (key: string, value: unknown) => setForm((current) => ({ ...current, [key]: value }));
  async function save() {
    const api = window.desktopApp?.aiAnalysis; if (!api) return; setBusy(true);
    const payload: AiSettingsUpdate = { service: "ai_nexus", provider: "AI Nexus", endpoint: form.endpoint, model: form.model, apiContract: form.apiContract, authType: form.authType, organization: form.organization, project: form.project, contextWindow: form.contextWindow, timeoutMs: form.timeoutMs, maxOutputTokens: form.maxOutputTokens, maxRetries: form.maxRetries, secret: form.secret, preserveSecret: !form.secret, expectedEnvSha256: snapshot.env.sha256, expectedEnvMtimeMs: snapshot.env.mtimeMs };
    const result = await api.saveSettings(payload); setBusy(false); if (result.snapshot) setSnapshot(result.snapshot); notice(result.ok ? "AI Nexus 設定已寫入本機 .env。 / AI Nexus settings saved." : `${result.errorCode}: ${result.message}`);
  }
  return <Panel title="AI Nexus" subtitle="OpenAI-compatible company service. Endpoint and token are used only by Electron main process." actions={<Pill tone={source.connectionStatus === "passed" ? "green" : "slate"}>{source.connectionStatus}</Pill>}>
    <div className="grid min-w-0 grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label="Endpoint" value={form.endpoint} onChange={(value) => update("endpoint", value)} /><Field label="Model" value={form.model} onChange={(value) => update("model", value)} /><Field label={source.secretConfigured ? "Token (leave blank to keep)" : "Token"} type="password" value={form.secret} onChange={(value) => update("secret", value)} /><label className="text-xs font-black text-slate-700"><span className="mb-1 block">API Contract</span><select className="field" value={form.apiContract} onChange={(event) => update("apiContract", event.target.value)}><option value="chat_completions">Chat Completions</option><option value="responses">Responses-compatible</option></select></label><Field label="Timeout (ms)" type="number" value={String(form.timeoutMs)} onChange={(value) => update("timeoutMs", Number(value))} /><div className="flex items-end gap-2"><button className="btn btn-primary flex-1" disabled={busy || !snapshot.env.found || !snapshot.env.supported} onClick={() => void save()}><Save size={15} />Save</button><button className="btn" disabled={busy} onClick={async () => { const result = await window.desktopApp?.aiAnalysis?.testConnection("ai_nexus"); notice(result?.ok ? "AI Nexus connection passed." : `${result?.errorCode}: ${result?.message}`); }}><Play size={15} />Test</button></div></div>
  </Panel>;
}

function TestChat({ snapshot, notice }: { snapshot: AiAnalysisSnapshot; notice: (value: string) => void }) {
  const [service, setService] = useState<AiServiceKey>("chatgpt"); const [text, setText] = useState(""); const [messages, setMessages] = useState<AiChatMessage[]>([]); const [busy, setBusy] = useState(false);
  const ready = service === "chatgpt" ? snapshot.chatgpt.state === "connected" : snapshot.env.aiNexus.connectionStatus === "passed";
  async function send() { const api = window.desktopApp?.aiAnalysis; if (!api || !text.trim() || !ready) return; const value = text.trim(); setText(""); setBusy(true); const result = await api.chat({ service, sessionId: "diagnostic-chat", messages: [...messages.map((item) => ({ role: item.role, text: item.text })), { role: "user", text: value }] }); setBusy(false); if (result.message) setMessages((items) => [...items, { ...result.message!, id: `${result.message!.id}-user`, role: "user", text: value }, result.message!]); else notice(`${result.errorCode}: ${result.messageText}`); }
  return <Panel title="Safe Test Chat" subtitle="Plain text only. Do not paste Jira data, credentials, or company secrets." actions={<select className="field w-auto" value={service} onChange={(event) => setService(event.target.value as AiServiceKey)}><option value="chatgpt">ChatGPT</option><option value="ai_nexus">AI Nexus</option></select>}><div className="max-h-64 space-y-2 overflow-y-auto rounded-md bg-slate-50 p-3">{messages.length ? messages.map((item) => <div key={item.id} className={`max-w-[88%] rounded-md p-2 text-sm ${item.role === "user" ? "ml-auto bg-blue-600 text-white" : "bg-white text-slate-800"}`}>{item.text}</div>) : <div className="py-8 text-center text-xs font-semibold text-muted">No messages</div>}</div><div className="mt-3 flex min-w-0 gap-2"><input className="field min-w-0 flex-1" value={text} onChange={(event) => setText(event.target.value)} placeholder={ready ? "Type a safe test message" : "Selected provider is not ready"} disabled={!ready || busy} /><button className="btn btn-primary" disabled={!ready || busy || !text.trim()} onClick={() => void send()}>{busy ? <LoaderCircle className="animate-spin" size={15} /> : <Send size={15} />}Send</button></div></Panel>;
}

function Diagnostics({ snapshot, setSnapshot, notice }: { snapshot: AiAnalysisSnapshot; setSnapshot: (value: AiAnalysisSnapshot) => void; notice: (value: string) => void }) { return <div className="space-y-4"><ChatGptDiagnostics snapshot={snapshot} setSnapshot={setSnapshot} notice={notice} /><AiNexusSettings snapshot={snapshot} setSnapshot={setSnapshot} notice={notice} /><TestChat snapshot={snapshot} notice={notice} /></div>; }

function Workspace({ snapshot, setSnapshot, notice, goResults }: { snapshot: AiAnalysisSnapshot; setSnapshot: (value: AiAnalysisSnapshot) => void; notice: (value: string) => void; goResults: () => void }) {
  const api = window.desktopApp?.aiAnalysis; const [mode, setMode] = useState<AiAnalyzerMode>("OFFLINE_RULE"); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const dataset = snapshot.pendingDatasets.find((item) => item.datasetId === snapshot.selectedPendingDatasetId) ?? null;
  useEffect(() => setSelected(dataset?.diffs.filter((item) => item.substantive).map((item) => item.sourceDiffId) ?? []), [dataset?.datasetId]);
  const ready = Boolean(dataset && snapshot.rules?.valid && selected.length) && (mode === "OFFLINE_RULE" || mode === "CHATGPT" && snapshot.chatgpt.state === "connected" || mode === "AI_NEXUS" && snapshot.env.aiNexus.connectionStatus === "passed");
  async function chooseRules() { const result = await api?.chooseRules(); if (result?.snapshot) setSnapshot(result.snapshot); if (result && !result.canceled && !result.ok) notice(`${result.errorCode}: ${result.message}`); }
  async function choosePending() { const result = await api?.choosePending(); if (result?.snapshot) setSnapshot(result.snapshot); if (result && !result.canceled && !result.ok) notice(`${result.errorCode}: ${result.message}`); }
  async function start() { if (!api || !dataset) return; setBusy(true); const service = mode === "CHATGPT" ? "chatgpt" : "ai_nexus"; const result = await api.start({ mode, datasetId: dataset.datasetId, selectedDiffIds: selected, service }); setBusy(false); if (result.snapshot) setSnapshot(result.snapshot); notice(result.ok ? "分析完成，結果等待人工覆核。 / Analysis completed; human review required." : `${result.errorCode ?? result.run?.progress.errorCode}: ${result.message ?? result.run?.progress.message}`); if (result.run) goResults(); }
  const modes: Array<{ id: AiAnalyzerMode; title: string; detail: string }> = [{ id: "CHATGPT", title: "ChatGPT", detail: "Codex App Server · subscription access" }, { id: "AI_NEXUS", title: "AI Nexus", detail: "Company OpenAI-compatible service" }, { id: "OFFLINE_RULE", title: "Offline Rule Analyzer", detail: "Deterministic · no network" }];
  return <div className="space-y-4"><Panel title="Analysis Provider" subtitle="Choose one provider for this run."><div className="grid grid-cols-1 gap-3 md:grid-cols-3">{modes.map((item) => <button key={item.id} className={`min-w-0 rounded-md border p-4 text-left ${mode === item.id ? "border-blue-500 bg-blue-50" : "border-line bg-white"}`} onClick={() => setMode(item.id)}><b className="block text-sm">{item.title}</b><span className="mt-1 block break-words text-xs font-semibold text-muted">{item.detail}</span></button>)}</div></Panel><Panel title="Analysis Inputs" subtitle="Rules and pending-analysis data are validated before a run."><div className="grid gap-3 md:grid-cols-2"><button className="btn justify-start" onClick={() => void chooseRules()}><FolderOpen size={15} />{snapshot.rules?.valid ? `${snapshot.rules.rulesDirectoryLabel} · ${snapshot.rules.catalogCount} skills` : "Choose rules folder"}</button><button className="btn justify-start" onClick={() => void choosePending()}><Upload size={15} />{dataset ? `${dataset.fileName} · ${dataset.diffs.length} diffs` : "Open pending-analysis JSON"}</button></div>{dataset ? <div className="mt-3 max-h-64 overflow-y-auto rounded-md border border-line"><table className="w-full min-w-[620px] text-left text-xs"><thead className="sticky top-0 bg-slate-100"><tr><th className="p-2">Use</th><th className="p-2">Issue</th><th className="p-2">Field</th><th className="p-2">Event time</th></tr></thead><tbody>{dataset.diffs.map((diff) => <tr key={diff.sourceDiffId} className="border-t border-line"><td className="p-2"><input type="checkbox" checked={selected.includes(diff.sourceDiffId)} onChange={() => setSelected((items) => items.includes(diff.sourceDiffId) ? items.filter((id) => id !== diff.sourceDiffId) : [...items, diff.sourceDiffId])} /></td><td className="p-2 font-mono">{diff.issueKey}</td><td className="p-2">{diff.fieldName}</td><td className="p-2">{diff.eventTime}</td></tr>)}</tbody></table></div> : null}<div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-xs font-bold text-muted">{selected.length} selected</span><button className="btn btn-primary" disabled={!ready || busy} onClick={() => void start()}>{busy ? <LoaderCircle className="animate-spin" size={15} /> : <Play size={15} />}Run Analysis</button></div>{!ready && mode === "CHATGPT" ? <div className="mt-3 flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-900"><AlertTriangle className="shrink-0" size={15} />Sign in with ChatGPT and load a verified dataset and rules before analysis.</div> : null}</Panel></div>;
}

function Results({ snapshot, setSnapshot, notice }: { snapshot: AiAnalysisSnapshot; setSnapshot: (value: AiAnalysisSnapshot) => void; notice: (value: string) => void }) {
  const run = snapshot.runs.find((item) => item.runId === snapshot.selectedRunId) ?? snapshot.runs[0]; const api = window.desktopApp?.aiAnalysis;
  if (!run) return <Panel title="Analysis Results"><div className="py-16 text-center text-sm font-semibold text-muted">No analysis result yet.</div></Panel>;
  async function exportRun(format: AiExportFormat) { const result = await api?.exportRun({ runId: run.runId, format }); notice(result?.canceled ? "Export cancelled." : result?.filePath ? `Saved: ${result.filePath}` : `${result?.errorCode}: ${result?.message}`); }
  async function review(resultId: string, status: "CONFIRMED" | "REJECTED") { const result = await api?.review({ runId: run.runId, resultId, status, note: "Reviewed in v0.3.9 UI" }); if (result?.snapshot) setSnapshot(result.snapshot); }
  return <div className="space-y-4"><Panel title="Run Summary" subtitle={run.runId} actions={<div className="flex flex-wrap gap-2">{(["json", "csv", "html"] as AiExportFormat[]).map((format) => <button key={format} className="btn" disabled={run.status !== "completed"} onClick={() => void exportRun(format)}><Download size={14} />{format.toUpperCase()}</button>)}</div>}><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div><span className="text-[10px] font-black text-muted">STATUS</span><div className="mt-1"><Pill tone={run.status === "completed" ? "green" : run.status === "failed" ? "red" : "blue"}>{run.status}</Pill></div></div><div><span className="text-[10px] font-black text-muted">PROVIDER</span><b className="mt-1 block break-words text-sm">{run.provider}</b></div><div><span className="text-[10px] font-black text-muted">RESULTS</span><b className="mt-1 block text-xl">{run.results.length}</b></div><div><span className="text-[10px] font-black text-muted">PROGRESS</span><b className="mt-1 block text-xl">{run.progress.completedDiffs}/{run.progress.totalDiffs}</b></div></div>{run.progress.errorCode ? <div className="mt-3 rounded-md border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-800">{run.progress.errorCode}: {run.progress.message}</div> : null}</Panel><Panel title="Per-diff Review" subtitle="AI candidates remain pending until a person confirms or rejects them."><div className="space-y-3">{run.results.map((result) => <article key={result.resultId} className="min-w-0 rounded-md border border-line p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><b className="break-all font-mono text-xs text-blue-700">{result.sourceDiffId}</b><div className="mt-2 flex flex-wrap gap-2"><Pill tone={result.status === "CONFIRMED" ? "green" : result.status === "REJECTED" ? "red" : "amber"}>{result.status}</Pill><Pill>{result.candidates.length} candidates</Pill></div></div><div className="flex gap-2"><button className="btn py-2" onClick={() => void review(result.resultId, "CONFIRMED")}><Check size={14} />Confirm</button><button className="btn py-2" onClick={() => void review(result.resultId, "REJECTED")}><Square size={14} />Reject</button></div></div><div className="mt-3 grid gap-2 md:grid-cols-2">{result.candidates.map((candidate) => <div key={candidate.skillId} className="rounded-md bg-slate-50 p-3"><div className="flex flex-wrap justify-between gap-2"><b className="text-xs">{candidate.skillId} · {candidate.skillName}</b><span className="text-xs font-black text-blue-700">{candidate.score ?? "-"}</span></div><p className="mt-2 break-words text-xs font-semibold leading-relaxed text-muted">{candidate.reason}</p></div>)}</div></article>)}</div></Panel></div>;
}

export function AiAnalysisFunctionalPage() {
  const [snapshot, setSnapshot] = useState<AiAnalysisSnapshot | null>(null); const [activeTab, setActiveTab] = useState<Tab>("diagnostics"); const [message, setMessage] = useState<string | null>(null); const { appendDebugLog } = useOutletContext<AppOutletContext>();
  useEffect(() => { const api = window.desktopApp?.aiAnalysis; if (!api) return; void api.getSnapshot().then(async (value) => { setSnapshot(value); if (value.chatgpt.state === "stopped") { await api.startChatGpt(); setSnapshot(await api.getSnapshot()); } }).catch((error) => setMessage(String(error))); return api.onSnapshotChanged(setSnapshot); }, []);
  useEffect(() => { if (message) appendDebugLog("analysis", [`[INFO] ${message.replace(/(?:token|authorization)\s*[:=]\s*\S+/gi, "$1: [masked]")}`]); }, [message]);
  const tabs = useMemo(() => [{ id: "diagnostics" as const, label: "AI 診斷與登入", sub: "AI Diagnostics" }, { id: "workspace" as const, label: "分析工作區", sub: "Analysis Workspace" }, { id: "results" as const, label: "分析結果", sub: "Analysis Results" }], []);
  return <div className="min-w-0 pb-8"><header className="mb-4 flex min-w-0 items-start gap-3"><span className="mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-blue-600 text-white"><Sparkles size={20} /></span><div className="min-w-0"><div className="text-[10px] font-black uppercase text-blue-600">Skill Analysis Workspace</div><h1 className="mt-1 text-2xl font-black leading-tight text-ink">AI Analysis</h1><p className="mt-1 max-w-4xl text-sm font-semibold leading-relaxed text-muted">以 ChatGPT、AI Nexus 或離線規則分析已驗證的 pending-analysis evidence，並保留人工覆核與可追溯輸出。</p></div></header><div className="mb-4 grid min-w-0 grid-cols-1 gap-2 md:grid-cols-3" role="tablist">{tabs.map((tab) => <button key={tab.id} role="tab" aria-selected={activeTab === tab.id} className={`min-w-0 rounded-md border px-4 py-3 text-left ${activeTab === tab.id ? "border-blue-500 bg-blue-50 text-blue-800" : "border-line bg-white text-slate-700"}`} onClick={() => setActiveTab(tab.id)}><b className="block text-sm">{tab.label}</b><span className="text-[11px] font-semibold">{tab.sub}</span></button>)}</div>{message ? <div className="mb-4 flex items-start gap-2 rounded-md border border-blue-200 bg-blue-50 p-3 text-sm font-bold text-blue-900"><Check className="mt-0.5 shrink-0" size={15} /><span className="min-w-0 flex-1 break-words">{message}</span><button aria-label="Dismiss" onClick={() => setMessage(null)}>×</button></div> : null}{!snapshot ? <div className="flex min-h-72 items-center justify-center"><LoaderCircle className="animate-spin text-blue-600" /></div> : activeTab === "diagnostics" ? <Diagnostics snapshot={snapshot} setSnapshot={setSnapshot} notice={setMessage} /> : activeTab === "workspace" ? <Workspace snapshot={snapshot} setSnapshot={setSnapshot} notice={setMessage} goResults={() => setActiveTab("results")} /> : <Results snapshot={snapshot} setSnapshot={setSnapshot} notice={setMessage} />}<footer className="mt-5 flex flex-wrap items-center gap-2 rounded-md border border-slate-200 bg-slate-50 p-3 text-xs font-semibold text-slate-600"><Database size={14} />Only completed analysis results use the separate AI Analysis SQLite database. Jira source databases remain read-only.</footer></div>;
}
