import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";
import { initializeAppRoot } from "../electron/appPaths.js";
import { prepareSingleRunOutputSchema } from "../electron/aiAnalysisOutputSchemaV0313.js";
import { buildRequestPackage, loadRequestPackage, CORE_ANALYSIS_INSTRUCTION, PROVIDER_DELIVERY_MODE } from "../electron/aiAnalysisRequestPackageV0314.js";
import { AiAnalysisRunArchive, loadArchivedRuns, readConversationPage, verifyConversationLog } from "../electron/aiAnalysisRunArchiveV0314.js";
import { validateCanonicalResponseSemantics } from "../electron/aiAnalysisResponseContractV0314.js";
import { redactChatGptText, redactChatGptTextComplete } from "../electron/chatGptRedactor.js";
import { stageVisibleProviderResponse } from "../electron/aiAnalysisSingleRunV0311.js";
import { evaluateFormalPersistenceGate } from "../electron/aiAnalysisV0312.js";

const hash = (value: string | Buffer) => crypto.createHash("sha256").update(value).digest("hex");
const root = fs.mkdtempSync(path.join(os.tmpdir(), "jaa-v0314-"));
initializeAppRoot(root);
const source = path.join(root, "pending.json");
const rulesDir = path.join(root, "rules"); fs.mkdirSync(rulesDir);
const manifestPath = path.join(rulesDir, "Skill_Analysis_Rule_Set_Manifest.md");
const catalogPath = path.join(rulesDir, "Skill_Catalog.md");
const commonPath = path.join(rulesDir, "Common_Rules.md");
fs.writeFileSync(source, JSON.stringify({ records: [{ reference: { sourceRecordStableId: "stable-1", evidenceId: "evidence-1" }, text: "原始證據" }] }), "utf8");
fs.writeFileSync(manifestPath, "manifest exact\n", "utf8"); fs.writeFileSync(catalogPath, "catalog exact\n", "utf8"); fs.writeFileSync(commonPath, "rules exact\n", "utf8");
const metadata = (kind: "manifest" | "catalog" | "rules", filePath: string) => ({ kind, fileName: path.basename(filePath), fullPath: filePath, version: "test", sha256: hash(fs.readFileSync(filePath)), sizeBytes: fs.statSync(filePath).size, mtimeMs: fs.statSync(filePath).mtimeMs, status: "verified" as const });
const rules: any = { valid: true, rulesDirectoryLabel: "rules", rulesDirectoryPath: rulesDir, snapshotId: "rules-sha", ruleSetId: "rules-1", manifestSchemaVersion: "1", catalogVersion: "1", commonRulesVersion: "1", classificationEngineVersion: "offline-rule-v1", parserVersion: "ai-rules-parser-v1", files: [metadata("manifest", manifestPath), metadata("catalog", catalogPath), metadata("rules", commonPath)], catalogCount: 1, catalog: [{ id: "SKILL_1", name: "Skill", group: "Group", catalogStatus: "review-draft", detailDescription: null }], commonRulesNormalized: [], errors: [] };
const dataset: any = { datasetId: "dataset-1", fileName: path.basename(source), sourceFilePath: source, sourceFileSha256: hash(fs.readFileSync(source)), eventCount: 1, diffs: [{ sourceDiffId: "stable-1" }] };
const archive = new AiAnalysisRunArchive("analysis_11111111-1111-1111-1111-111111111111", new Date("2026-08-13T01:02:03.004Z"));
const schema = prepareSingleRunOutputSchema();
const request = buildRequestPackage({ runId: archive.runId, runDirectory: archive.directory, dataset, rules, selectedRecordCount: 1, supplementalInstruction: "Prefer direct evidence.", outputSchemaCanonicalJson: schema.canonicalJson });
assert.equal(request.requestPackage.deliveryMode, PROVIDER_DELIVERY_MODE);
assert.equal(request.requestPackage.documents.length, 6);
assert.equal(request.requestPackage.inlineBlockCount, 5);
assert.equal(request.requestPackage.nativeFileCount, 0);
assert.ok(request.requestPackage.documents.every((item) => item.byteIdentical && item.complete && !item.truncated));
assert.ok(request.prompt.includes(fs.readFileSync(source, "utf8")));
assert.ok(request.prompt.includes("manifest exact\n"));
assert.ok(request.prompt.includes("catalog exact\n"));
assert.ok(request.prompt.includes("rules exact\n"));
assert.ok(request.prompt.includes(CORE_ANALYSIS_INSTRUCTION));
assert.equal(hash(request.prompt), request.requestPackage.finalProviderPayloadSha256);
assert.equal(fs.readFileSync(path.join(archive.directory, "request-package", "pending-analysis.json")).equals(fs.readFileSync(source)), true);
assert.equal(request.requestPackage.pendingSourceSha256, dataset.sourceFileSha256);
assert.equal(request.requestPackage.inputStableIdSetSha256, hash("stable-1"));
fs.writeFileSync(source, "source changed after immutable snapshot", "utf8");
assert.equal(loadRequestPackage(archive.directory).prompt, request.prompt);

const long = "x".repeat(20_000) + " Token: secret-value";
assert.equal(redactChatGptText(long).length, 8192);
assert.ok(redactChatGptTextComplete(long).length > 8192);
assert.equal(redactChatGptTextComplete(long).includes("secret-value"), false);
const event1 = archive.append("system_event", "APP_ONLY", "Run created");
const event2 = archive.append("assistant_delta", "CHATGPT_VISIBLE", "a".repeat(12_000));
assert.equal(event2.previousHash, event1.hash);
const logPath = path.join(archive.directory, "conversation.jsonl");
assert.deepEqual(verifyConversationLog(logPath), { valid: true, eventCount: 2, terminalHash: event2.hash, invalidSequence: null });
assert.equal(readConversationPage(archive.directory, 0, 1).hasMore, true);

const run: any = { runId: archive.runId, status: "running", startedAt: "2026-08-13T01:02:03.004Z", progress: { status: "running", stage: "receiving_response", errorCode: null, message: "running" } };
archive.writeManifest(run);
const recovered = loadArchivedRuns().find((item) => item.runId === archive.runId)!;
assert.equal(recovered.status, "interrupted");
assert.equal(recovered.progress.errorCode, "RUN_INTERRUPTED");
const tamperedArchive = new AiAnalysisRunArchive("analysis_22222222-2222-2222-2222-222222222222", new Date("2026-08-13T01:02:04.005Z"));
tamperedArchive.append("system_event", "APP_ONLY", "durable event");
fs.appendFileSync(path.join(tamperedArchive.directory, "conversation.jsonl"), "{truncated", "utf8");
assert.equal(verifyConversationLog(path.join(tamperedArchive.directory, "conversation.jsonl")).valid, false);

const responseText = JSON.stringify({ records: Array.from({ length: 400 }, (_, index) => ({ index, text: "完整回覆".repeat(30) })) });
assert.ok(Buffer.byteLength(responseText) > 8192);
const staged = stageVisibleProviderResponse(archive.directory, responseText);
assert.equal(staged.rawSha256, hash(responseText));
assert.equal(fs.readFileSync(staged.rawFilePath, "utf8"), responseText);
assert.equal(hash(fs.readFileSync(staged.rawFilePath)), staged.rawSha256);
assert.equal(zlib.gunzipSync(fs.readFileSync(staged.filePath)).toString("utf8"), responseText);

const baseRecord = { sourceRecordStableId: "stable-1", classificationStatus: "UNKNOWN", reviewAttention: "STANDARD_REVIEW", dispositionReason: "Unknown", exclusionReason: null, unknownReason: "Evidence insufficient", reviewReason: null, matchedRuleIds: [], analyses: [], negativeChecks: [] };
const oldConflict = validateCanonicalResponseSemantics({ records: [baseRecord] });
assert.equal(oldConflict.valid, false);
assert.equal(oldConflict.findings[0].path, "records[0].negativeChecks");
assert.equal(oldConflict.findings[0].jsonPath, "$.records[0].negativeChecks");
assert.equal(oldConflict.findings[0].jsonPointer, "/records/0/negativeChecks");
assert.equal(oldConflict.findings[0].sourceRecordStableId, "stable-1");
const matched = validateCanonicalResponseSemantics({ records: [{ ...baseRecord, classificationStatus: "MATCHED", matchedRuleIds: ["RULE_DIRECT"], analyses: [{ skillId: "SKILL_1", candidateStatus: "MATCHED", statusReason: "Direct", catalogDetailAvailable: true, positiveEvidenceRefs: ["e1"], negativeChecks: [] }] }] });
assert.equal(matched.valid, true);
const detailMissing = validateCanonicalResponseSemantics({ records: [{ ...baseRecord, classificationStatus: "CATALOG_DETAIL_MISSING", reviewAttention: "NEEDS_REVIEW", analyses: [{ skillId: "SKILL_1", candidateStatus: "CATALOG_DETAIL_MISSING", statusReason: "Catalog detail missing", catalogDetailAvailable: false, positiveEvidenceRefs: ["e1"], negativeChecks: [{ ruleId: "CATALOG_DETAIL_REQUIRED", passed: false }] }] }] });
assert.equal(detailMissing.valid, true);
const lostCandidate = validateCanonicalResponseSemantics({ records: [{ ...baseRecord, classificationStatus: "CATALOG_DETAIL_MISSING" }] });
assert.equal(lostCandidate.findings[0].path, "records[0].analyses");
const review = validateCanonicalResponseSemantics({ records: [{ ...baseRecord, classificationStatus: "NEEDS_REVIEW", reviewAttention: "NEEDS_REVIEW", reviewReason: "Ambiguous evidence", analyses: [{ skillId: "SKILL_1", candidateStatus: "NEEDS_REVIEW", statusReason: "Ambiguous evidence", catalogDetailAvailable: true, positiveEvidenceRefs: ["e1"], negativeChecks: [] }] }] });
assert.equal(review.valid, true);

const ids = Array.from({ length: 117 }, (_, index) => `stable-${index}`);
const partialGate = evaluateFormalPersistenceGate({ providerStatus: "completed", inputIds: ids, outputIds: ids.slice(0, 116), catalogInvalidSkillIds: [], responseSaved: true, jsonValid: true });
assert.equal(partialGate.passed, false); assert.equal(partialGate.formalJsonAllowed, false); assert.equal(partialGate.sqliteAllowed, false);

console.log("v0.3.14 Request Package, conversation durability, response evidence, semantic matrix, and formal gate tests passed (43 assertions).");
