import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { AI_DECISION_CONFIDENCE_VALUES, AI_DECISION_CONTRACT_VERSION, AI_DECISION_STATUSES, buildDecisionFixture, createDecisionArraySchema, validateDecisionArray, type AiDecision } from "../electron/aiAnalysisDecisionContractV0322.js";
import { EVIDENCE_NORMALIZER_VERSION, normalizeEvidence, normalizeEvidenceSet, quoteIsTraceable } from "../electron/aiAnalysisEvidenceNormalizerV0322.js";
import { buildRunIssueSnapshots, calculateIssueStatistics, normalizeIssueKey } from "../electron/aiAnalysisIssueSnapshotV0322.js";
import { evaluateDecisionQuality, QUALITY_THRESHOLDS, sqliteQualityGate } from "../electron/aiAnalysisQualityV0322.js";
import { DEFAULT_ANALYSIS_INSTRUCTION } from "../electron/aiAnalysisInstructionV0322.js";
import { freezeBoundHtmlTemplate, HTML_RENDERER_VERSION, renderCanonicalHtml } from "../electron/aiAnalysisHtmlRendererV0322.js";
import { loadV0322RulesSnapshot, parseHtmlReportTemplateV0322, V0322_RULE_BINDING, V0322_RULE_HASHES } from "../electron/aiAnalysisRulesV0322.js";
import { persistCompletedRunV0322 } from "../electron/aiAnalysisSqliteV0322.js";

const root = path.resolve(__dirname, "../..");
const rulesDirectory = path.join(root, "rules", "v0.3.22");
const quote = "GC 卡在 FTLGCCheckProgram()";
const source = [{ evidenceRef: "pae_fixture", normalizedText: `[Fail Phenomenon]\n${quote}` }];
const finding = (skillId = "GC_006", value = quote) => ({ skillId, confidence: 0.9 as const, evidenceQuotes: [{ evidenceRef: "pae_fixture", quote: value }], evidenceExplanation: "此內容直接描述 GC 流程停滯。", negativeChecks: ["已排除只有一般 Log 關鍵字而沒有 GC 行為證據的情況"], rationale: "此證據符合技能的技術行為定義" });
const decision = (status: typeof AI_DECISION_STATUSES[number]): AiDecision => ({ recordIndex: 0, status, confidence: status === "EXCLUDED" || status === "FAILED" ? 0 : 0.9, skillFindings: ["CLASSIFIED", "CATALOG_DETAIL_MISSING"].includes(status) ? [finding()] : [], recordNegativeChecks: status === "EXCLUDED" ? ["非技能活動"] : [], unknownReasons: status === "UNKNOWN" ? ["技術證據不足"] : [], rationale: `${status} 的完整判定理由` });
const expected = { recordCount: 1, catalogSkillIds: ["GC_006", "GC_007"], evidenceByRecord: [source] };

assert.equal(AI_DECISION_CONTRACT_VERSION, "jaa-ai-analysis-decisions-v3");
assert.deepEqual(AI_DECISION_CONFIDENCE_VALUES, [0, 0.3, 0.6, 0.9]);
assert.equal(createDecisionArraySchema(1).items.additionalProperties, false);
for (const status of AI_DECISION_STATUSES) assert.equal(validateDecisionArray([decision(status)], expected).valid, true, status);
assert.equal(validateDecisionArray({ records: [decision("CLASSIFIED")] }, expected).valid, false);
assert.equal(validateDecisionArray(JSON.stringify([decision("CLASSIFIED")]), expected).valid, false);
assert.equal(validateDecisionArray([], expected).findings[0].code, "AI_DECISION_COUNT_MISMATCH");
assert.equal(validateDecisionArray([{ ...decision("CLASSIFIED"), extra: true }], expected).schemaValid, false);
assert.equal(validateDecisionArray([{ ...decision("CLASSIFIED"), confidence: 0.8 }], expected).valid, false);
assert.equal(validateDecisionArray([{ ...decision("CLASSIFIED"), skillFindings: [finding(), finding()] }], expected).findings.some((item) => item.code === "AI_DECISION_DUPLICATE_SKILL_ID"), true);
assert.equal(validateDecisionArray([{ ...decision("CLASSIFIED"), skillFindings: [finding("NO_SUCH_SKILL")] }], expected).valid, false);
assert.equal(validateDecisionArray([{ ...decision("CLASSIFIED"), skillFindings: [finding("GC_006", "not in source")] }], expected).findings.some((item) => item.code === "AI_EVIDENCE_QUOTE_UNTRACEABLE"), true);
assert.equal(validateDecisionArray([{ ...decision("CLASSIFIED"), skillIds: ["GC_006"] }], expected).valid, false, "Decision v2 cannot pass v3");
assert.deepEqual(validateDecisionArray([decision("CLASSIFIED")], expected).derivedSkillIds, [["GC_006"]]);

const commentRaw = JSON.stringify({ commentId: "1", contentStatus: "current", body: "[Fail Phenomenon]\\r\\nGC 卡在 FTLGCCheckProgram()\\r\\n\\r\\n[Root Cause]\\r\\n因未考量到 Copy Data 追上 Build GCSA" });
const normalized = normalizeEvidence({ evidenceRef: "pae_fixture", rawText: commentRaw, sourceProvenance: "comment", fieldName: "Comment" });
assert.equal(normalized.mode, "parsed"); assert.match(normalized.normalizedText, /\[Fail Phenomenon\]\nGC 卡在/); assert.doesNotMatch(normalized.normalizedText, /commentId|contentStatus|\\r\\n|\{\"/); assert.equal(normalized.rawText, commentRaw); assert.equal(quoteIsTraceable(normalized, quote), true);
const fallback = normalizeEvidence({ evidenceRef: "bad", rawText: "{broken" }); assert.equal(fallback.mode, "fallback"); assert.equal(fallback.normalizedText, "{broken");
const markup = normalizeEvidence({ evidenceRef: "markup", rawText: "!screen.png|width=200! [Jira|https://invalid.local] <script>alert(1)</script>" }); assert.match(markup.normalizedText, /\[圖片: screen.png\]/); assert.match(markup.normalizedText, /<script>/);
const normalizationSet = normalizeEvidenceSet([{ evidenceRef: "one", rawText: commentRaw }, { evidenceRef: "two", rawText: "{broken" }]); assert.equal(normalizationSet.receipt.normalizerVersion, EVIDENCE_NORMALIZER_VERSION); assert.equal(normalizationSet.receipt.fallbackCount, 1); assert.equal(normalizationSet.receipt.inputIdentitySha256.length, 64);

assert.equal(normalizeIssueKey(" copgen1-1 "), "COPGEN1-1");
const issueKeys = Array.from({ length: 117 }, (_, index) => `PROJ-${index < 2 ? index + 1 : 3 + ((index - 2) % 26)}`); const issueStats = calculateIssueStatistics(issueKeys.map((issueKey) => ({ issueKey })));
assert.equal(issueStats.activityEventCount, 117); assert.equal(issueStats.uniqueIssueCount, 28); assert.equal(issueStats.issuesWithMultipleEvents, 26); assert.equal(issueStats.duplicateEventOccurrences, 89);
const enrichment = buildRunIssueSnapshots(["abc-1", " ABC-1 ", "abc-2"], (key) => key === "ABC-1" ? { issueId: "1", issueKey: key, projectKey: "ABC", issueType: { id: "1", name: "Bug" }, priority: { id: "2", name: "Major" }, jiraStatus: { id: "3", name: "Resolved" } } : null, { capturedAt: "2026-08-19T00:00:00.000Z" });
assert.equal(enrichment.receipt.expectedUniqueIssueCount, 2); assert.equal(enrichment.receipt.resolvedCount, 1); assert.equal(enrichment.warning, "report_enrichment_warning");

const passedQuality = evaluateDecisionQuality([decision("CLASSIFIED")]); assert.equal(passedQuality.status, "PASSED"); assert.equal(sqliteQualityGate(passedQuality).eligible, true);
const repeated = Array.from({ length: 4 }, (_, recordIndex) => ({ ...decision("CLASSIFIED"), recordIndex, skillFindings: [{ ...finding(), evidenceExplanation: "相同說明", rationale: "相同理由" }] })); const warningQuality = evaluateDecisionQuality(repeated); assert.equal(warningQuality.status, "WARNING"); assert.ok(warningQuality.metrics.evidenceExplanationExactDuplicateRatio.ratio > QUALITY_THRESHOLDS.exactDuplicateRatioWarning); assert.equal(sqliteQualityGate(warningQuality).eligible, false); assert.equal(sqliteQualityGate(warningQuality, { accepted: true, canonicalSha256: "a".repeat(64), runId: "run", acceptedAt: "2026-08-19T00:00:00.000Z" }).eligible, true);
const blockedQuality = evaluateDecisionQuality([decision("CLASSIFIED")], { untraceableEvidenceQuoteCount: 1 }); assert.equal(blockedQuality.status, "BLOCKED"); assert.equal(sqliteQualityGate(blockedQuality, { accepted: true, canonicalSha256: "a".repeat(64), runId: "run", acceptedAt: "2026-08-19T00:00:00.000Z" }).eligible, false);
assert.equal(evaluateDecisionQuality(buildDecisionFixture(2), { legacy: true }).status, "LEGACY_UNVERIFIED");
assert.match(DEFAULT_ANALYSIS_INSTRUCTION, /JAA-CHATGPT-ZH-TW-0\.3\.22/); assert.match(DEFAULT_ANALYSIS_INSTRUCTION, /skillFindings/); assert.match(DEFAULT_ANALYSIS_INSTRUCTION, /0、0\.3、0\.6、0\.9/);

const rules = loadV0322RulesSnapshot(rulesDirectory, [root]); assert.equal(rules.valid, true); assert.equal(rules.catalogCount, 279); assert.equal(rules.files.length, 3); assert.equal(rules.htmlReportTemplate?.providerVisible, false); assert.equal(rules.htmlReportTemplate?.sha256, V0322_RULE_HASHES.template);
const templateText = fs.readFileSync(path.join(rulesDirectory, V0322_RULE_BINDING.templateFileName), "utf8"); const template = parseHtmlReportTemplateV0322(templateText).contract; assert.equal(template.templateVersion, "1.2.0"); assert.equal(template.filters.sameFieldOperator, "OR"); assert.equal(template.filters.crossFieldOperator, "AND");

function result(runId: string, index: number) { return { resultId: `result_${crypto.createHash("sha256").update(`${runId}:${index}`).digest("hex").slice(0, 24)}`, sourceDiffId: `source-${index}`, sourceContentHash: `hash-${index}`, sourceEvidenceSnapshot: { issueKey: `PROJ-${index % 28 + 1}`, actor: `Actor ${index % 3}`, eventTimestamp: `2026-08-${String(index % 19 + 1).padStart(2, "0")}T00:00:00Z`, fieldName: index % 2 ? "Comment" : "Description", sourceProvenance: "fixture", addedText: [quote], removedText: [] }, evidenceRefs: ["pae_fixture"], recordIndex: index, sourceRecordStableId: `stable-${index}`, evidenceId: "pae_fixture", decisionConfidence: 0.9, decisionRationale: "完整理由", recordNegativeChecks: [], derivedSkillIds: ["GC_006"], classificationStatus: "MATCHED", reviewStatus: "PENDING_REVIEW", candidates: [{ skillId: "GC_006", skillName: "GC skill", group: "GC", score: 90, confidence: 0.9, positiveEvidenceRefs: ["pae_fixture"], negativeEvidenceRefs: [], matchedRuleIds: [], evidenceQuote: quote, evidenceQuotes: [{ evidenceRef: "pae_fixture", quote }], evidenceExplanation: "直接描述 GC", skillRationale: "符合 GC", reason: "符合 GC", status: "PENDING_REVIEW" }], status: "PENDING_REVIEW", analyzerVersion: "fixture", requestTraceId: null, usage: { inputTokens: 1, cachedInputTokens: 0, outputTokens: 1, reasoningTokens: 0, totalTokens: 2, availability: "actual", estimatedInputTokens: null }, rawResultAvailable: true, reviewNote: "", reviewedAt: null }; }
function runFixture(runId: string, count: number) { const results = Array.from({ length: count }, (_, index) => result(runId, index)); return { runId, revision: 1, status: "completed", analyzerMode: "CHATGPT", sourceDatasetId: "dataset", sourceFileName: "pending.json", sourceFileSha256: "b".repeat(64), sourceDatabaseId: "source-db", jiraServerFingerprint: "jira", selectedDiffIds: results.map((item) => item.sourceDiffId), rules, provider: "chatgpt", model: "fixture", apiContract: "responses", configFingerprint: null, startedAt: "2026-08-19T00:00:00.000Z", completedAt: "2026-08-19T00:01:00.000Z", progress: { status: "completed", totalBatches: 0, completedBatches: 0, failedBatches: 0, currentBatch: 0, totalDiffs: count, completedDiffs: count, requestCount: 1, retryCount: 0, elapsedMs: 60000, usage: results[0]?.usage, message: "done", errorCode: null }, results, analyzedFileName: "analyzed.json", analyzedFilePath: null, databasePath: null, canonicalRecordCount: count, receivedDecisionCount: count, sqliteCommittedRecordCount: 0, htmlRenderStatus: "not_started", instructionMode: "STANDARD_FORMAL", decisionContractVersion: AI_DECISION_CONTRACT_VERSION, evidenceNormalizerVersion: EVIDENCE_NORMALIZER_VERSION, qualityGate: { contractVersion: "jaa-ai-analysis-quality-v1", status: "PASSED", warnings: [], blockers: [], metrics: {} }, lifecycle: { providerTurnStatus: "completed", inputStatus: "ready", modelInputStatus: "delivered", analysisStatus: "completed", artifactStatus: "published", validationStatus: "completed", canonicalAssemblyStatus: "completed", htmlRenderStatus: "not_started", sqliteStatus: "eligible", overallStatus: "completed", lastSuccessfulStage: "CANONICAL_ASSEMBLY_COMPLETED", firstFailedStage: null, rootErrorCode: null, derivedStatusCodes: [], canonicalStatus: "created", analysisStarted: true, analysisCompleted: true, completedCount: count, decisionPreparedCount: count, updatedAtLocal: "2026-08-19 08:01:00", updatedAtUtc: "2026-08-19T00:01:00.000Z" } } as any; }

const temp = fs.mkdtempSync(path.join(os.tmpdir(), "jaa-v0322-"));
try {
  const runDirectory = path.join(temp, "run"); fs.mkdirSync(runDirectory, { recursive: true }); const frozen = freezeBoundHtmlTemplate(runDirectory, rules); assert.equal(path.basename(frozen.filePath), V0322_RULE_BINDING.templateFileName); assert.equal(frozen.rendererVersion, HTML_RENDERER_VERSION);
  const run = runFixture("analysis_117", 117); run.results[0].sourceEvidenceSnapshot.addedText = ["<script>alert(1)</script>"]; const canonicalPath = path.join(runDirectory, "analysis-result.json"); fs.writeFileSync(canonicalPath, JSON.stringify({ schemaName: "jira-activity-analyzer.analyzed-analysis", schemaVersion: "test", run }, null, 2));
  const first = renderCanonicalHtml({ canonicalResultPath: canonicalPath, frozenTemplatePath: frozen.filePath, outputHtmlPath: path.join(runDirectory, "first.html"), renderContext: { renderedAt: "2026-08-19T00:01:00.000Z", appVersion: "0.3.22", buildTime: "fixed", packagedSourceCommit: "fixed" } }); const second = renderCanonicalHtml({ canonicalResultPath: canonicalPath, frozenTemplatePath: frozen.filePath, outputHtmlPath: path.join(runDirectory, "second.html"), renderContext: { renderedAt: "2026-08-19T00:01:00.000Z", appVersion: "0.3.22", buildTime: "fixed", packagedSourceCommit: "fixed" } });
  assert.equal(first.receipt.outputHtmlSha256, second.receipt.outputHtmlSha256); for (const marker of ["Advanced Multi-select Filters", "Field Visibility", "Field Data Dictionary", "match any", "visible Unique Issues", "Readable Evidence", "Raw Added", "Content-Security-Policy"]) assert.match(first.html, new RegExp(marker)); assert.doesNotMatch(first.html, /https?:\/\//i); assert.doesNotMatch(first.html, /fetch\(|XMLHttpRequest|WebSocket/i); assert.match(first.html, /\\u003cscript/);
  run.analyzedFilePath = canonicalPath; const db = path.join(temp, "test.sqlite3"); const dataset = { datasetId: "dataset", sourceFileSha256: "b".repeat(64), sourceDatabaseId: "source-db", jiraServerFingerprint: "jira" } as any; assert.equal(persistCompletedRunV0322(db, dataset, run, { qualityReport: passedQuality }).committedRecordCount, 117); assert.equal(persistCompletedRunV0322(db, dataset, run, { qualityReport: passedQuality }).status, "already_committed"); assert.throws(() => persistCompletedRunV0322(path.join(temp, "blocked.sqlite3"), dataset, run, { qualityReport: blockedQuality }), /Quality Gate/);
} finally { fs.rmSync(temp, { recursive: true, force: true }); }

console.log("v0.3.22 Decision v3 / evidence / quality / snapshot / HTML / SQLite focused tests passed");
