import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { bundledRuleSelectionV0324, loadExplicitRulesSnapshotV0324, parseHtmlReportTemplateV0324, V0324_RULE_BINDING, V0324_RULE_HASHES } from "../electron/aiAnalysisRulesV0324.js";
import { buildCompactPayload } from "../electron/aiAnalysisSingleRunV0311.js";
import { buildEvidenceSegmentCatalogV0324, modelPayloadWithSegmentsV0324 } from "../electron/aiAnalysisEvidenceSegmenterV0324.js";
import { createDecisionArraySchemaV0324, getDecisionContractDescriptorV0324, validateDecisionArrayV0324, type AiDecisionV0324 } from "../electron/aiAnalysisDecisionContractV0324.js";
import { evaluateDecisionQualityV0324 } from "../electron/aiAnalysisQualityV0324.js";
import { assembleCanonicalResultsV0324 } from "../electron/aiAnalysisArtifactsV0324.js";
import { buildIssueSnapshotProfilesV0324, buildReportDataPackageV0324, durableJsonWriteV0324, readReportDataPackageV0324 } from "../electron/aiAnalysisReportDataPackageV0324.js";
import { renderReportDataPackageHtmlV0324 } from "../electron/aiAnalysisHtmlRendererV0324.js";
import { DEFAULT_ANALYSIS_INSTRUCTION } from "../electron/aiAnalysisInstructionV0324.js";
import type { AiAnalysisRun, AiPendingDataset } from "../shared/aiAnalysisContract.js";

const root = path.resolve(__dirname, "../.."); const rulesDir = path.join(root, "rules", "v0.3.24"); const rules = loadExplicitRulesSnapshotV0324(bundledRuleSelectionV0324(rulesDir));
assert.equal(rules.valid, true); assert.equal(rules.selectionMode, "BUNDLED_DEFAULT"); assert.equal(rules.roleDocuments?.length, 4); assert.equal(rules.roleDocuments?.filter((item) => item.providerVisible).length, 3); assert.equal(rules.roleDocuments?.find((item) => item.role === "html_template")?.providerVisible, false); assert.deepEqual(Object.fromEntries(rules.roleDocuments!.map((item) => [item.role, item.sha256])), V0324_RULE_HASHES); assert.equal(rules.ruleSetId, V0324_RULE_BINDING.ruleSetId);
const template = parseHtmlReportTemplateV0324(fs.readFileSync(path.join(rulesDir, V0324_RULE_BINDING.templateFileName), "utf8")).contract; assert.equal(template.schemaVersion, "jaa-html-report-template-v5"); assert.ok(template.requiredCapabilities.includes("REPORT_DATA_PACKAGE_V1")); assert.equal(template.security.allowRemoteResource, false); assert.match(DEFAULT_ANALYSIS_INSTRUCTION, /JAA-CHATGPT-ZH-TW-0[.]3[.](24|25)/); assert.match(DEFAULT_ANALYSIS_INSTRUCTION, /PRIMARY_CHANGE/);
assert.equal(createDecisionArraySchemaV0324(17).minItems, 17); assert.equal(getDecisionContractDescriptorV0324(117).schemaVersion, "jaa-ai-analysis-decisions-v4");

function dataset(count: number): AiPendingDataset { const diffs = Array.from({ length: count }, (_, index) => ({ sourceDiffId: `stable-${index}`, sourceContentHash: `hash-${index}`, evidenceId: `evidence-${index}`, activityEventId: `event-${index}`, issueKey: `SYN-${index % 28 + 1}`, projectKey: "SYN", actorId: `actor-${index % 3}`, actorDisplayName: `Synthetic Actor ${index % 3}`, fieldId: "description", fieldName: "Description", eventTime: `2026-08-${String(index % 20 + 1).padStart(2, "0")}T00:00:00.000Z`, sourceProvenance: "synthetic-test", diffStatus: "changed", substantive: true, addedLineCount: 2, removedLineCount: 1, diffHunks: [{ oldStart: 1, oldLines: 2, newStart: 1, newLines: 3, lines: [{ type: "context", text: `函式 context ${index}` }, { type: "removed", text: `old exact ${index}` }, { type: "added", text: `新增技術證據 ${index}\u00a0保留 NBSP` }] }] })); return { datasetId: `synthetic-${count}`, fileName: `synthetic-${count}.json`, schemaVersion: "synthetic-v1", sourceFileSha256: "a".repeat(64), sourceDatabaseId: "synthetic-db", jiraServerFingerprint: "synthetic-jira", jiraServerHost: "jira.example.invalid", sourceSchemaVersion: 1, sourceView: "synthetic", createdAt: "2026-08-20T00:00:00.000Z", eventCount: count, eligibleCount: count, issues: Math.min(count, 28), projects: 1, integrityStatus: "verified", errors: [], diffs }; }
function fixture(count: number) { const data = dataset(count); const compact = buildCompactPayload(data, data.diffs.map((diff) => diff.sourceDiffId), rules).payload; const segments = buildEvidenceSegmentCatalogV0324(`analysis_synthetic_${count}`, data, compact); const byRecord = new Map(segments.segments.filter((segment) => segment.evidenceRoleEligibility === "PRIMARY_CHANGE").map((segment) => [segment.recordIndex, segment])); const skillId = rules.catalog[0].id; const decisions: AiDecisionV0324[] = compact.records.map((record, recordIndex) => { const segment = byRecord.get(recordIndex)!; return { recordIndex, status: "CLASSIFIED", confidence: 0.9, skillFindings: [{ skillId, confidence: 0.9, evidenceQuotes: [{ evidenceRef: segment.evidenceRef, evidenceSegmentId: segment.evidenceSegmentId, quote: segment.exactText, evidenceRole: "PRIMARY_CHANGE" }], evidenceExplanation: `記錄 ${recordIndex} 的新增技術證據直接支持此技能。`, negativeChecks: ["已排除純 workflow 或一般狀態文字。"], rationale: `依 record ${recordIndex} 的獨立 primary change 判定。` }], recordNegativeChecks: [], unknownReasons: [], rationale: `Synthetic record ${recordIndex} has exact traceable change evidence.` }; }); return { data, compact, segments, decisions }; }
for (const count of [17, 117]) { const value = fixture(count); assert.equal(value.segments.recordCount, count); assert.equal(new Set(value.segments.segments.map((segment) => segment.evidenceSegmentId)).size, value.segments.segmentCount); const validation = validateDecisionArrayV0324(value.decisions, { recordCount: count, catalogSkillIds: rules.catalog.map((item) => item.id), sourceRecordStableIds: value.compact.records.map((record) => record.sourceRecordStableId), evidenceSegments: value.segments.segments }); assert.equal(validation.valid, true, `${count} synthetic records`); assert.equal(validation.actualCount, count); assert.equal(modelPayloadWithSegmentsV0324(value.compact, value.segments).records.length, count); }
const one = fixture(1); const expected = { recordCount: 1, catalogSkillIds: rules.catalog.map((item) => item.id), sourceRecordStableIds: ["stable-0"], evidenceSegments: one.segments.segments };
const wrongQuote = structuredClone(one.decisions); wrongQuote[0].skillFindings[0].evidenceQuotes[0].quote += " "; assert.ok(validateDecisionArrayV0324(wrongQuote, expected).findings.some((item) => item.code === "EVIDENCE_QUOTE_NOT_EXACT"));
const context = one.segments.segments.find((segment) => segment.evidenceRoleEligibility === "SUPPORTING_CONTEXT")!; const contextOnly = structuredClone(one.decisions); contextOnly[0].skillFindings[0].evidenceQuotes = [{ evidenceRef: context.evidenceRef, evidenceSegmentId: context.evidenceSegmentId, quote: context.exactText, evidenceRole: "SUPPORTING_CONTEXT" }]; const contextValidation = validateDecisionArrayV0324(contextOnly, expected); assert.ok(contextValidation.findings.some((item) => item.code === "PRIMARY_CHANGE_REQUIRED")); assert.ok(contextValidation.findings.some((item) => item.code === "CONTEXT_ONLY_CLASSIFICATION"));
const nonSubstantive = structuredClone(one.decisions); const primary = one.segments.segments.find((segment) => segment.evidenceRoleEligibility === "PRIMARY_CHANGE")!; primary.exactText = "done"; nonSubstantive[0].skillFindings[0].evidenceQuotes[0].quote = "done"; const nonSubValidation = validateDecisionArrayV0324(nonSubstantive, { ...expected, evidenceSegments: one.segments.segments }); assert.ok(evaluateDecisionQualityV0324(nonSubValidation).findings.some((item) => item.code === "NON_SUBSTANTIVE_EVIDENCE"));

const snapshots = buildIssueSnapshotProfilesV0324({ jiraServerIdentity: "synthetic-jira", issueKeys: ["syn-1", "SYN-1", "SYN-2"], snapshots: [{ issueId: "1", issueKey: "SYN-1", projectKey: "SYN", issueType: { id: "1", name: "Bug" }, priority: { id: "2", name: "Major" }, jiraStatus: { id: "3", name: "Open" } }], capturedAt: "2026-08-20T00:00:00.000Z", sourceDatabaseIdentity: "synthetic-db" }); assert.equal(snapshots.length, 2); assert.equal(snapshots[0].project.state, "PRESENT"); assert.equal(snapshots[1].project.state, "SOURCE_UNAVAILABLE");
const valid = validateDecisionArrayV0324(one.decisions, expected); const quality = evaluateDecisionQualityV0324(valid); const results = assembleCanonicalResultsV0324({ runId: "analysis_synthetic", compact: one.compact, decisions: one.decisions, rules, analyzerVersion: "synthetic", jiraServerIdentity: "synthetic-jira", requestTraceId: null }); assert.equal(results[0].issueSnapshot, undefined); assert.ok(results[0].issueSnapshotReference);
const run = { runId: "analysis_synthetic", revision: 1, status: "completed", analyzerMode: "CHATGPT", sourceDatasetId: one.data.datasetId, sourceFileName: one.data.fileName, sourceFileSha256: one.data.sourceFileSha256, sourceDatabaseId: one.data.sourceDatabaseId, jiraServerFingerprint: one.data.jiraServerFingerprint, selectedDiffIds: ["stable-0"], provider: "chatgpt", model: "synthetic", apiContract: "responses", configFingerprint: null, rules, startedAt: "2026-08-20T00:00:00.000Z", completedAt: "2026-08-20T00:01:00.000Z", progress: { runId: "analysis_synthetic", status: "completed", totalBatches: 0, completedBatches: 0, failedBatches: 0, currentBatch: 0, totalDiffs: 1, completedDiffs: 1, requestCount: 1, retryCount: 0, elapsedMs: 1, usage: results[0].usage, message: "done", errorCode: null }, results, analyzedFileName: "synthetic.json", analyzedFilePath: null, databasePath: null } as AiAnalysisRun;
const formal = buildReportDataPackageV0324({ mode: "FORMAL_CANONICAL", run, rules, results, segments: one.segments.segments, issueSnapshots: snapshots, validationFindings: [], quality, canonicalSha256: "b".repeat(64) }); assert.equal(formal.records.length, 1); assert.equal(formal.issueSnapshots.length, 2); assert.equal(formal.schemaVersion, "jaa-analysis-report-data-package-v1");
const diagnostic = buildReportDataPackageV0324({ mode: "DIAGNOSTIC_NON_CANONICAL", run, rules, results, segments: one.segments.segments, issueSnapshots: snapshots, validationFindings: contextValidation.findings, quality: evaluateDecisionQualityV0324(contextValidation) }); assert.equal(diagnostic.sourceCanonicalIdentity, null);
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "jaa-v0324-")); try { const formalPath = path.join(temp, "formal.json"), diagnosticPath = path.join(temp, "diagnostic.json"); durableJsonWriteV0324(formalPath, formal); durableJsonWriteV0324(diagnosticPath, diagnostic); assert.equal(readReportDataPackageV0324(formalPath).packageSha256, formal.packageSha256); const first = renderReportDataPackageHtmlV0324({ reportDataPackagePath: formalPath, templatePath: path.join(rulesDir, V0324_RULE_BINDING.templateFileName), outputDirectory: temp }); const waitUntil = Date.now() + 5; while (Date.now() < waitUntil) { /* ensure non-overwriting timestamp changes */ } const second = renderReportDataPackageHtmlV0324({ reportDataPackagePath: formalPath, templatePath: path.join(rulesDir, V0324_RULE_BINDING.templateFileName), outputDirectory: temp }); const diag = renderReportDataPackageHtmlV0324({ reportDataPackagePath: diagnosticPath, templatePath: path.join(rulesDir, V0324_RULE_BINDING.templateFileName), outputDirectory: temp }); assert.notEqual(first.receipt.outputHtmlPath, second.receipt.outputHtmlPath); const formalHtml = fs.readFileSync(first.receipt.outputHtmlPath, "utf8"); assert.match(formalHtml, /正式 Canonical Report/); assert.match(formalHtml, /Advanced Multi-select Filters/); assert.match(formalHtml, /Field Visibility/); assert.match(formalHtml, /Field Data Dictionary/); assert.match(formalHtml, /匯出目前篩選 CSV/); assert.match(formalHtml, /目前顯示/); assert.match(formalHtml, /page-size/); assert.match(fs.readFileSync(diag.receipt.outputHtmlPath, "utf8"), /非正式診斷預覽/); assert.equal(first.receipt.providerUsed, false); assert.equal(first.receipt.databaseUsed, false); assert.doesNotMatch(formalHtml, /fetch\(|XMLHttpRequest|WebSocket/); } finally { fs.rmSync(temp, { recursive: true, force: true }); }
console.log("v0.3.24 four-role / Decision v4 / Segmenter / Validator / Package / offline renderer focused tests passed");
