import crypto from "node:crypto";
import type { EvidenceRoleEligibility, EvidenceSegmentV0324 } from "./aiAnalysisEvidenceSegmenterV0324.js";

export const AI_DECISION_CONTRACT_VERSION_V0324 = "jaa-ai-analysis-decisions-v4" as const;
export const AI_ARTIFACT_SUBMISSION_VERSION_V0324 = "jaa-analysis-artifact-submission-v4" as const;
export const AI_DECISION_CONFIDENCE_VALUES_V0324 = [0, 0.3, 0.6, 0.9] as const;
export const AI_DECISION_STATUSES_V0324 = ["CLASSIFIED", "UNKNOWN", "NEEDS_REVIEW", "EXCLUDED", "CATALOG_DETAIL_MISSING", "FAILED"] as const;
export type DecisionStatusV0324 = typeof AI_DECISION_STATUSES_V0324[number];
export type DecisionConfidenceV0324 = typeof AI_DECISION_CONFIDENCE_VALUES_V0324[number];
export type EvidenceRoleV0324 = Exclude<EvidenceRoleEligibility, "INELIGIBLE">;
export type EvidenceQuoteV0324 = { evidenceRef: string; evidenceSegmentId: string; quote: string; evidenceRole: EvidenceRoleV0324 };
export type SkillFindingV0324 = { skillId: string; confidence: DecisionConfidenceV0324; evidenceQuotes: EvidenceQuoteV0324[]; evidenceExplanation: string; negativeChecks: string[]; rationale: string };
export type AiDecisionV0324 = { recordIndex: number; status: DecisionStatusV0324; confidence: DecisionConfidenceV0324; skillFindings: SkillFindingV0324[]; recordNegativeChecks: string[]; unknownReasons: string[]; rationale: string };
export type ValidationFindingV0324 = { code: string; severity: "ERROR" | "WARNING"; stage: "SCHEMA" | "SEMANTIC" | "EVIDENCE" | "QUALITY" | "QUALITY_GATE"; recordIndex: number | null; sourceRecordStableId: string | null; skillId: string | null; evidenceSegmentId: string | null; jsonPointer: string; expected: unknown; observed: unknown; message: string };
export type DecisionValidationV0324 = { contractVersion: typeof AI_DECISION_CONTRACT_VERSION_V0324; contractSha256: string; valid: boolean; schemaValid: boolean; semanticValid: boolean; evidenceValid: boolean; attributionValid: boolean; expectedCount: number; actualCount: number; semanticValidCount: number; decisions: AiDecisionV0324[]; findings: ValidationFindingV0324[]; schemaFindings: ValidationFindingV0324[]; semanticFindings: ValidationFindingV0324[]; evidenceFindings: ValidationFindingV0324[]; warnings: string[]; distribution: Record<DecisionStatusV0324, number>; derivedSkillIds: string[][] };
export type DecisionExpectedV0324 = { recordCount: number; catalogSkillIds: string[]; sourceRecordStableIds: string[]; evidenceSegments: EvidenceSegmentV0324[] };

export const AI_DECISION_FIELDS_V0324 = ["recordIndex", "status", "confidence", "skillFindings", "recordNegativeChecks", "unknownReasons", "rationale"] as const;
export const AI_SKILL_FINDING_FIELDS_V0324 = ["skillId", "confidence", "evidenceQuotes", "evidenceExplanation", "negativeChecks", "rationale"] as const;
export const AI_EVIDENCE_QUOTE_FIELDS_V0324 = ["evidenceRef", "evidenceSegmentId", "quote", "evidenceRole"] as const;
const object = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const text = (value: unknown) => typeof value === "string" ? value : "";
const trimmed = (value: unknown) => text(value).trim();
const strings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const confidence = (value: unknown): value is DecisionConfidenceV0324 => typeof value === "number" && AI_DECISION_CONFIDENCE_VALUES_V0324.includes(value as DecisionConfidenceV0324);
const canonical = (value: unknown): unknown => Array.isArray(value) ? value.map(canonical) : object(value) ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])) : value;
const sha256 = (value: string) => crypto.createHash("sha256").update(value, "utf8").digest("hex");

export function createDecisionArraySchemaV0324(expectedRecordCount: number) {
  const stringArray = { type: "array", items: { type: "string" } } as const;
  const quote = { type: "object", additionalProperties: false, required: [...AI_EVIDENCE_QUOTE_FIELDS_V0324], properties: { evidenceRef: { type: "string", minLength: 1 }, evidenceSegmentId: { type: "string", minLength: 1 }, quote: { type: "string", minLength: 1 }, evidenceRole: { type: "string", enum: ["PRIMARY_CHANGE", "SUPPORTING_CONTEXT"] } } } as const;
  const finding = { type: "object", additionalProperties: false, required: [...AI_SKILL_FINDING_FIELDS_V0324], properties: { skillId: { type: "string", minLength: 1 }, confidence: { type: "number", enum: [...AI_DECISION_CONFIDENCE_VALUES_V0324] }, evidenceQuotes: { type: "array", minItems: 1, items: quote }, evidenceExplanation: { type: "string", minLength: 1 }, negativeChecks: stringArray, rationale: { type: "string", minLength: 1 } } } as const;
  return { type: "array", minItems: expectedRecordCount, maxItems: expectedRecordCount, items: { type: "object", additionalProperties: false, required: [...AI_DECISION_FIELDS_V0324], properties: { recordIndex: { type: "integer", minimum: 0, maximum: Math.max(0, expectedRecordCount - 1) }, status: { type: "string", enum: [...AI_DECISION_STATUSES_V0324] }, confidence: { type: "number", enum: [...AI_DECISION_CONFIDENCE_VALUES_V0324] }, skillFindings: { type: "array", items: finding }, recordNegativeChecks: stringArray, unknownReasons: stringArray, rationale: { type: "string", minLength: 1 } } } } as const;
}
export function getDecisionContractDescriptorV0324(expectedRecordCount: number) { const schema = createDecisionArraySchemaV0324(expectedRecordCount); const canonicalJson = JSON.stringify(canonical({ schemaVersion: AI_DECISION_CONTRACT_VERSION_V0324, schema })); return { schemaVersion: AI_DECISION_CONTRACT_VERSION_V0324, schema, canonicalJson, bytes: Buffer.byteLength(canonicalJson), sha256: sha256(canonicalJson) }; }
export function createArtifactSubmissionSchemaV0324(expectedRecordCount: number) { return { type: "object", additionalProperties: false, required: ["schemaVersion", "runId", "sourceSha256", "rulesSnapshotId", "expectedRecordCount", "decisionContractVersion", "decisionContractSha256", "decisionsDocument", "analysisReportMarkdown", "finalSummaryTraditionalChinese"], properties: { schemaVersion: { const: AI_ARTIFACT_SUBMISSION_VERSION_V0324 }, runId: { type: "string" }, sourceSha256: { type: "string" }, rulesSnapshotId: { type: "string" }, expectedRecordCount: { const: expectedRecordCount }, decisionContractVersion: { const: AI_DECISION_CONTRACT_VERSION_V0324 }, decisionContractSha256: { const: getDecisionContractDescriptorV0324(expectedRecordCount).sha256 }, decisionsDocument: createDecisionArraySchemaV0324(expectedRecordCount), analysisReportMarkdown: { type: "string", minLength: 1 }, finalSummaryTraditionalChinese: { type: "string", minLength: 1 } } } as const; }

function push(findings: ValidationFindingV0324[], input: Omit<ValidationFindingV0324, "severity"> & { severity?: ValidationFindingV0324["severity"] }) { findings.push({ severity: input.severity ?? "ERROR", ...input }); }
function blankDecision(index: number): AiDecisionV0324 { return { recordIndex: index, status: "FAILED", confidence: 0, skillFindings: [], recordNegativeChecks: [], unknownReasons: [], rationale: "" }; }

export function validateDecisionArrayV0324(value: unknown, expected: DecisionExpectedV0324): DecisionValidationV0324 {
  const findings: ValidationFindingV0324[] = []; const catalog = new Set(expected.catalogSkillIds); const segments = new Map(expected.evidenceSegments.map((segment) => [segment.evidenceSegmentId, segment]));
  if (!Array.isArray(value)) push(findings, { code: "DECISION_ROOT_TYPE_MISMATCH", stage: "SCHEMA", recordIndex: null, sourceRecordStableId: null, skillId: null, evidenceSegmentId: null, jsonPointer: "", expected: "direct JSON array", observed: value === null ? "null" : typeof value, message: "Decision v4 必須是直接 JSON 陣列，不接受 wrapper、字串或 code fence。" });
  const rows = Array.isArray(value) ? value : []; if (rows.length !== expected.recordCount) push(findings, { code: "COUNT_OR_IDENTITY_MISMATCH", stage: "SCHEMA", recordIndex: null, sourceRecordStableId: null, skillId: null, evidenceSegmentId: null, jsonPointer: "", expected: expected.recordCount, observed: rows.length, message: "Decision 筆數必須與輸入記錄完全一致。" });
  const seen = new Set<number>(); const decisions: AiDecisionV0324[] = rows.map((raw, outputIndex) => {
    const row = object(raw) ? raw : {}; const pointer = `/${outputIndex}`; const index = Number.isInteger(row.recordIndex) ? Number(row.recordIndex) : -1; const stableId = expected.sourceRecordStableIds[index] ?? null;
    if (!object(raw) || AI_DECISION_FIELDS_V0324.some((field) => !(field in row)) || Object.keys(row).some((key) => !AI_DECISION_FIELDS_V0324.includes(key as never))) push(findings, { code: "DECISION_SCHEMA_MISMATCH", stage: "SCHEMA", recordIndex: index >= 0 ? index : null, sourceRecordStableId: stableId, skillId: null, evidenceSegmentId: null, jsonPointer: pointer, expected: AI_DECISION_FIELDS_V0324, observed: Object.keys(row), message: "Decision 欄位必須完整且不可包含額外欄位。" });
    if (index !== outputIndex || index < 0 || index >= expected.recordCount || seen.has(index)) push(findings, { code: "COUNT_OR_IDENTITY_MISMATCH", stage: "SCHEMA", recordIndex: index >= 0 ? index : null, sourceRecordStableId: stableId, skillId: null, evidenceSegmentId: null, jsonPointer: `${pointer}/recordIndex`, expected: outputIndex, observed: row.recordIndex, message: "recordIndex 必須依序且唯一覆蓋 0..N-1。" }); else seen.add(index);
    const status = AI_DECISION_STATUSES_V0324.includes(String(row.status) as DecisionStatusV0324) ? String(row.status) as DecisionStatusV0324 : "FAILED"; if (!AI_DECISION_STATUSES_V0324.includes(String(row.status) as DecisionStatusV0324)) push(findings, { code: "STATUS_MATRIX_VIOLATION", stage: "SCHEMA", recordIndex: index, sourceRecordStableId: stableId, skillId: null, evidenceSegmentId: null, jsonPointer: `${pointer}/status`, expected: AI_DECISION_STATUSES_V0324, observed: row.status, message: "Decision status 不在允許矩陣內。" });
    const rowConfidence = confidence(row.confidence) ? row.confidence : 0; if (!confidence(row.confidence)) push(findings, { code: "DECISION_SCHEMA_MISMATCH", stage: "SCHEMA", recordIndex: index, sourceRecordStableId: stableId, skillId: null, evidenceSegmentId: null, jsonPointer: `${pointer}/confidence`, expected: AI_DECISION_CONFIDENCE_VALUES_V0324, observed: row.confidence, message: "Confidence 必須使用 0、0.3、0.6、0.9。" });
    const rawFindings = Array.isArray(row.skillFindings) ? row.skillFindings : []; const skillIds = new Set<string>();
    const skillFindings = rawFindings.map((rawFinding, findingIndex): SkillFindingV0324 => {
      const item = object(rawFinding) ? rawFinding : {}; const fp = `${pointer}/skillFindings/${findingIndex}`; const skillId = trimmed(item.skillId);
      if (!object(rawFinding) || AI_SKILL_FINDING_FIELDS_V0324.some((field) => !(field in item)) || Object.keys(item).some((key) => !AI_SKILL_FINDING_FIELDS_V0324.includes(key as never))) push(findings, { code: "DECISION_SCHEMA_MISMATCH", stage: "SCHEMA", recordIndex: index, sourceRecordStableId: stableId, skillId: skillId || null, evidenceSegmentId: null, jsonPointer: fp, expected: AI_SKILL_FINDING_FIELDS_V0324, observed: Object.keys(item), message: "Skill Finding 欄位不完整或含有額外欄位。" });
      if (!catalog.has(skillId) || skillIds.has(skillId)) push(findings, { code: "CATALOG_SKILL_NOT_ALLOWED", stage: "SEMANTIC", recordIndex: index, sourceRecordStableId: stableId, skillId: skillId || null, evidenceSegmentId: null, jsonPointer: `${fp}/skillId`, expected: "單筆記錄中唯一且存在於綁定 Catalog", observed: skillId, message: "Skill ID 不在綁定 Catalog 或於同一記錄重複。" }); skillIds.add(skillId);
      const findingConfidence = confidence(item.confidence) ? item.confidence : 0; if (!confidence(item.confidence)) push(findings, { code: "DECISION_SCHEMA_MISMATCH", stage: "SCHEMA", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: null, jsonPointer: `${fp}/confidence`, expected: AI_DECISION_CONFIDENCE_VALUES_V0324, observed: item.confidence, message: "Skill confidence 必須使用指定列舉值。" });
      const rawQuotes = Array.isArray(item.evidenceQuotes) ? item.evidenceQuotes : []; const evidenceQuotes = rawQuotes.map((rawQuote, quoteIndex): EvidenceQuoteV0324 => {
        const quote = object(rawQuote) ? rawQuote : {}; const qp = `${fp}/evidenceQuotes/${quoteIndex}`; const segmentId = trimmed(quote.evidenceSegmentId); const source = segments.get(segmentId); const evidenceRole = quote.evidenceRole === "PRIMARY_CHANGE" ? "PRIMARY_CHANGE" : "SUPPORTING_CONTEXT"; const quoteText = text(quote.quote); const evidenceRef = trimmed(quote.evidenceRef);
        if (!object(rawQuote) || AI_EVIDENCE_QUOTE_FIELDS_V0324.some((field) => !(field in quote)) || Object.keys(quote).some((key) => !AI_EVIDENCE_QUOTE_FIELDS_V0324.includes(key as never))) push(findings, { code: "DECISION_SCHEMA_MISMATCH", stage: "SCHEMA", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: segmentId || null, jsonPointer: qp, expected: AI_EVIDENCE_QUOTE_FIELDS_V0324, observed: Object.keys(quote), message: "Evidence Quote v4 欄位不完整。" });
        if (!source || source.recordIndex !== index || source.evidenceRef !== evidenceRef) push(findings, { code: "EVIDENCE_SEGMENT_NOT_FOUND", stage: "EVIDENCE", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: segmentId || null, jsonPointer: `${qp}/evidenceSegmentId`, expected: "同一記錄內可追溯的 Evidence Segment", observed: { segmentId, evidenceRef }, message: "找不到此記錄所屬的 Evidence Segment。" });
        if (source && source.exactText !== quoteText) push(findings, { code: "EVIDENCE_QUOTE_NOT_EXACT", stage: "EVIDENCE", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: segmentId, jsonPointer: `${qp}/quote`, expected: source.exactText, observed: quoteText, message: "證據引文必須逐字等於 Evidence Segment，不可 trim、摘要或改寫。" });
        if (source && (source.evidenceRoleEligibility === "INELIGIBLE" || source.evidenceRoleEligibility !== evidenceRole)) push(findings, { code: "EVIDENCE_ROLE_MISMATCH", stage: "EVIDENCE", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: segmentId, jsonPointer: `${qp}/evidenceRole`, expected: source.evidenceRoleEligibility, observed: evidenceRole, message: "Evidence Role 與 Segment eligibility 不一致。" });
        return { evidenceRef, evidenceSegmentId: segmentId, quote: quoteText, evidenceRole };
      });
      if (!evidenceQuotes.length) push(findings, { code: "PRIMARY_CHANGE_REQUIRED", stage: "EVIDENCE", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: null, jsonPointer: `${fp}/evidenceQuotes`, expected: ">= 1 Evidence Quote", observed: 0, message: "每個 Skill Finding 至少需要一則證據。" });
      if (status === "CLASSIFIED" && !evidenceQuotes.some((quote) => quote.evidenceRole === "PRIMARY_CHANGE")) push(findings, { code: "PRIMARY_CHANGE_REQUIRED", stage: "EVIDENCE", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: null, jsonPointer: `${fp}/evidenceQuotes`, expected: ">= 1 PRIMARY_CHANGE", observed: evidenceQuotes.map((quote) => quote.evidenceRole), message: "CLASSIFIED 的每個 Skill Finding 都必須有獨立 PRIMARY_CHANGE 證據。" });
      if (status === "CLASSIFIED" && evidenceQuotes.length && evidenceQuotes.every((quote) => quote.evidenceRole === "SUPPORTING_CONTEXT")) push(findings, { code: "CONTEXT_ONLY_CLASSIFICATION", stage: "EVIDENCE", recordIndex: index, sourceRecordStableId: stableId, skillId, evidenceSegmentId: null, jsonPointer: `${fp}/evidenceQuotes`, expected: "PRIMARY_CHANGE", observed: "SUPPORTING_CONTEXT only", message: "僅有上下文不得判定為已分類。" });
      return { skillId, confidence: findingConfidence, evidenceQuotes, evidenceExplanation: trimmed(item.evidenceExplanation), negativeChecks: strings(item.negativeChecks), rationale: trimmed(item.rationale) };
    });
    const unknownReasons = strings(row.unknownReasons); const recordNegativeChecks = strings(row.recordNegativeChecks); const matrixInvalid = (["CLASSIFIED", "CATALOG_DETAIL_MISSING"].includes(status) && !skillFindings.length) || (["UNKNOWN", "EXCLUDED", "FAILED"].includes(status) && skillFindings.length > 0) || (status === "UNKNOWN" && !unknownReasons.length) || (status !== "UNKNOWN" && unknownReasons.length > 0);
    if (matrixInvalid) push(findings, { code: "STATUS_MATRIX_VIOLATION", stage: "SEMANTIC", recordIndex: index, sourceRecordStableId: stableId, skillId: null, evidenceSegmentId: null, jsonPointer: pointer, expected: "Decision v4 status matrix", observed: { status, skillFindingCount: skillFindings.length, unknownReasonCount: unknownReasons.length }, message: "Decision 狀態、Skill Findings 與 unknownReasons 不符合狀態矩陣。" });
    return { recordIndex: index, status, confidence: rowConfidence, skillFindings, recordNegativeChecks, unknownReasons, rationale: trimmed(row.rationale) };
  });
  while (decisions.length < expected.recordCount) decisions.push(blankDecision(decisions.length));
  const schemaFindings = findings.filter((item) => item.stage === "SCHEMA"), semanticFindings = findings.filter((item) => item.stage === "SEMANTIC"), evidenceFindings = findings.filter((item) => item.stage === "EVIDENCE"); const schemaValid = !schemaFindings.some((item) => item.severity === "ERROR"), semanticValid = !semanticFindings.some((item) => item.severity === "ERROR"), evidenceValid = !evidenceFindings.some((item) => item.severity === "ERROR"); const distribution = Object.fromEntries(AI_DECISION_STATUSES_V0324.map((status) => [status, decisions.filter((decision) => decision.status === status).length])) as Record<DecisionStatusV0324, number>;
  return { contractVersion: AI_DECISION_CONTRACT_VERSION_V0324, contractSha256: getDecisionContractDescriptorV0324(expected.recordCount).sha256, valid: schemaValid && semanticValid && evidenceValid, schemaValid, semanticValid, evidenceValid, attributionValid: evidenceValid, expectedCount: expected.recordCount, actualCount: rows.length, semanticValidCount: decisions.filter((decision) => !findings.some((finding) => finding.recordIndex === decision.recordIndex && finding.severity === "ERROR")).length, decisions, findings, schemaFindings, semanticFindings, evidenceFindings, warnings: [], distribution, derivedSkillIds: decisions.map((decision) => decision.skillFindings.map((finding) => finding.skillId)) };
}

export function parseAndValidateDecisionsV0324(raw: string, expected: DecisionExpectedV0324) { let parsed: unknown; try { parsed = JSON.parse(raw); } catch (error) { throw new Error(`AI_DECISION_JSON_INVALID: ${error instanceof Error ? error.message : String(error)}`); } return { document: { contractVersion: AI_DECISION_CONTRACT_VERSION_V0324, decisions: Array.isArray(parsed) ? parsed : [] }, validation: validateDecisionArrayV0324(parsed, expected) }; }