import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { AiAnalysisConversationEvent, AiAnalysisRun } from "../shared/aiAnalysisContract.js";
import { assertAppPath, ensureDir, getExportsDir } from "./appPaths.js";
import { redactChatGptTextComplete } from "./chatGptRedactor.js";
export const RUN_ARCHIVE_VERSION = "ai-analysis-run-archive-v1" as const;
export const CONVERSATION_EVENT_VERSION = "ai-analysis-conversation-event-v1" as const;
export const STREAM_EVENT_VERSION = "ai-analysis-provider-stream-event-v1" as const;
const sha256 = (value: string | Buffer) => crypto.createHash("sha256").update(value).digest("hex");
function localTime(date: Date) { return `${date.toLocaleString("sv-SE", { timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone })}.${String(date.getMilliseconds()).padStart(3, "0")}`; }
function localStamp(date: Date) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" }).formatToParts(date); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? "00"; return { year: get("year"), month: get("month"), day: get("day"), stamp: `${get("year")}${get("month")}${get("day")}_${get("hour")}${get("minute")}${get("second")}_${String(date.getMilliseconds()).padStart(3, "0")}` }; }
function atomicJson(filePath: string, value: unknown) { const target = assertAppPath(filePath); const temp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; fs.writeFileSync(temp, JSON.stringify(value, null, 2), { encoding: "utf8", flag: "wx" }); fs.renameSync(temp, target); }
function eventRole(type: AiAnalysisConversationEvent["type"]): AiAnalysisConversationEvent["role"] { return type === "user_message" ? "software" : type.startsWith("assistant") ? "assistant" : "system"; }
function contentType(type: AiAnalysisConversationEvent["type"]): AiAnalysisConversationEvent["contentType"] { return type === "provider_event" || type === "validation_event" || type === "artifact_event" ? "metadata" : "text"; }
export class AiAnalysisRunArchive {
  static reopen(runId: string, directory: string) { const archive = Object.create(AiAnalysisRunArchive.prototype) as AiAnalysisRunArchive; Object.defineProperty(archive, "runId", { value: runId, enumerable: true }); Object.defineProperty(archive, "directory", { value: assertAppPath(directory), enumerable: true }); const verified = verifyConversationLog(path.join(directory, "conversation.jsonl"), true); if (!verified.valid) throw new Error(`RUN_ARCHIVE_CONVERSATION_INTEGRITY_FAILED:${verified.invalidSequence}`); archive.sequence = verified.eventCount; archive.previousHash = verified.terminalHash; archive.streamSequence = countCompleteLines(path.join(directory, "provider-stream.jsonl")); return archive; }
  readonly directory: string; private sequence = 0; private streamSequence = 0; private previousHash: string | null = null;
  constructor(readonly runId: string, startedAt = new Date()) { const value = localStamp(startedAt); const root = ensureDir(path.join(getExportsDir(), "ai-analysis", "runs", value.year, value.month, value.day)); this.directory = assertAppPath(path.join(root, `${value.stamp}_${runId}`)); fs.mkdirSync(this.directory, { recursive: false }); fs.writeFileSync(path.join(this.directory, "conversation.jsonl"), "", { flag: "wx" }); fs.writeFileSync(path.join(this.directory, "provider-stream.jsonl"), "", { flag: "wx" }); }
  append(type: AiAnalysisConversationEvent["type"], visibility: AiAnalysisConversationEvent["visibility"], rawContent: string, metadata: Record<string, unknown> = {}) { const content = redactChatGptTextComplete(rawContent); const at = new Date(); const sequence = ++this.sequence; const base = { schemaVersion: CONVERSATION_EVENT_VERSION, runId: this.runId, sequence, eventId: `${this.runId}:event:${sequence}`, messageId: type === "user_message" || type === "assistant_message" ? `${this.runId}:message:${sequence}` : null, parentMessageId: null, role: eventRole(type), atLocal: localTime(at), atUtc: at.toISOString(), type, visibility, visibleToProvider: visibility === "CHATGPT_VISIBLE", contentType: contentType(type), content, contentByteLength: Buffer.byteLength(content), contentSha256: sha256(content), providerRequestId: typeof metadata.providerRequestId === "string" ? metadata.providerRequestId : null, threadId: typeof metadata.threadId === "string" ? metadata.threadId : null, turnId: typeof metadata.turnId === "string" ? metadata.turnId : null, metadata, previousHash: this.previousHash }; const hash = sha256(JSON.stringify(base)); const event: AiAnalysisConversationEvent = { ...base, hash }; this.appendFile("conversation.jsonl", JSON.stringify(event) + "\n"); this.previousHash = hash; if (type === "assistant_message" || type === "validation_event" || type === "artifact_event") this.writeConversationMarkdown(); return event; }
  appendProviderEvent(value: unknown) { const sanitized = JSON.parse(redactChatGptTextComplete(JSON.stringify(value))) as Record<string, unknown>; const received = new Date(); const payload = JSON.stringify(sanitized); const envelope = { schemaVersion: STREAM_EVENT_VERSION, runId: this.runId, sequence: ++this.streamSequence, receivedAtLocal: localTime(received), receivedAtUtc: received.toISOString(), providerEventType: String(sanitized.type ?? "unknown"), requestId: sanitized.requestId ?? null, threadId: sanitized.threadId ?? null, turnId: sanitized.turnId ?? null, redactionPolicyVersion: "chatgpt-redaction-v1", payloadBytes: Buffer.byteLength(payload), payloadSha256: sha256(payload), payload: sanitized }; this.appendFile("provider-stream.jsonl", JSON.stringify(envelope) + "\n"); }
  writeManifest(run: AiAnalysisRun, extra: Record<string, unknown> = {}) { const metric = (name: string) => { const filePath = path.join(this.directory, name); const bytes = fs.existsSync(filePath) ? fs.readFileSync(filePath) : Buffer.alloc(0); return { file: name, bytes: bytes.length, sha256: sha256(bytes) }; }; atomicJson(path.join(this.directory, "run-manifest.json"), { archiveVersion: RUN_ARCHIVE_VERSION, run, conversation: { eventCount: this.sequence, terminalHash: this.previousHash, ...metric("conversation.jsonl") }, providerStream: { eventCount: this.streamSequence, ...metric("provider-stream.jsonl") }, responseEvidence: { rawResponseSha256: run.providerResponseSha256 ?? null, canonicalResponseSha256: run.providerResponseCanonicalSha256 ?? null, gzipResponseSha256: run.providerResponseGzipSha256 ?? null }, ...extra }); if (["completed", "failed", "cancelled", "interrupted"].includes(run.status)) this.writeConversationMarkdown(); }
  private writeConversationMarkdown() { const filePath = path.join(this.directory, "conversation.jsonl"); const verification = verifyConversationLog(filePath); const events = fs.readFileSync(filePath, "utf8").split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as AiAnalysisConversationEvent); const body = events.map((event) => `## ${event.sequence}. ${event.role} / ${event.type}\n\n- Local: ${event.atLocal}\n- UTC: ${event.atUtc}\n- Visibility: ${event.visibility}\n- Content bytes: ${event.contentByteLength}\n- Content SHA-256: ${event.contentSha256}\n\n${event.content}\n`).join("\n"); const markdown = `# AI Analysis Conversation\n\nRun: ${this.runId}\nArchive: ${RUN_ARCHIVE_VERSION}\nSource event range: 1-${verification.eventCount}\nTerminal event hash: ${verification.terminalHash ?? "null"}\nDelivery evidence: see request-package/request-package-manifest.json\n\n${body}`; const target = path.join(this.directory, "conversation.md"); const temporary = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; fs.writeFileSync(temporary, markdown, { encoding: "utf8", flag: "wx" }); fs.renameSync(temporary, target); }
  private appendFile(name: string, value: string) { const file = fs.openSync(assertAppPath(path.join(this.directory, name)), "a"); try { const bytes = Buffer.from(value, "utf8"); let offset = 0; while (offset < bytes.length) offset += fs.writeSync(file, bytes, offset, bytes.length - offset); fs.fsyncSync(file); } finally { fs.closeSync(file); } }
}
function countCompleteLines(filePath: string) { if (!fs.existsSync(filePath)) return 0; return fs.readFileSync(filePath, "utf8").split(/\r?\n/).filter(Boolean).length; }
export function verifyConversationLog(filePath: string, recoverPartialTail = false) { const safe = assertAppPath(filePath); let raw = fs.readFileSync(safe, "utf8"); if (recoverPartialTail && raw && !raw.endsWith("\n")) { const lastNewline = raw.lastIndexOf("\n"); const partial = raw.slice(lastNewline + 1); const recoveryPath = path.join(path.dirname(safe), `conversation-partial-tail-${Date.now()}.txt`); fs.writeFileSync(recoveryPath, partial, { encoding: "utf8", flag: "wx" }); raw = lastNewline < 0 ? "" : raw.slice(0, lastNewline + 1); fs.writeFileSync(safe, raw, "utf8"); } const lines = raw.split(/\r?\n/).filter(Boolean); let previous: string | null = null; for (let index = 0; index < lines.length; index += 1) { let event: AiAnalysisConversationEvent; try { event = JSON.parse(lines[index]) as AiAnalysisConversationEvent; } catch { return { valid: false, eventCount: lines.length, terminalHash: previous, invalidSequence: index + 1 }; } const { hash, ...base } = event; if (event.sequence !== index + 1 || event.previousHash !== previous || sha256(JSON.stringify(base)) !== hash || event.contentByteLength !== Buffer.byteLength(event.content) || event.contentSha256 !== sha256(event.content)) return { valid: false, eventCount: lines.length, terminalHash: previous, invalidSequence: index + 1 }; previous = hash; } return { valid: true, eventCount: lines.length, terminalHash: previous, invalidSequence: null }; }
export function loadArchivedRuns() { const root = path.join(getExportsDir(), "ai-analysis", "runs"); if (!fs.existsSync(root)) return [] as AiAnalysisRun[]; const manifests: string[] = []; const visit = (folder: string) => { for (const entry of fs.readdirSync(folder, { withFileTypes: true })) { const target = path.join(folder, entry.name); if (entry.isDirectory()) visit(target); else if (entry.name === "run-manifest.json") manifests.push(target); } }; visit(root); return manifests.flatMap((manifestPath) => { try { const value = JSON.parse(fs.readFileSync(manifestPath, "utf8")); const run = value.run as AiAnalysisRun; run.runDirectory = path.dirname(manifestPath); const integrity = verifyConversationLog(path.join(run.runDirectory, "conversation.jsonl"), true); if (!integrity.valid) { run.status = "failed"; run.progress.status = "failed"; run.progress.stage = "failed"; run.progress.errorCode = "AI_RUN_ARCHIVE_FAILED"; run.progress.message = `Conversation archive integrity failed at sequence ${integrity.invalidSequence}.`; return [run]; } if (["running", "retrying", "cancelling"].includes(run.status)) { run.status = "interrupted"; run.progress.status = "interrupted"; run.progress.stage = "failed"; run.progress.errorCode = "RUN_INTERRUPTED"; run.progress.message = "Run was interrupted before a durable terminal state was recorded."; } return [run]; } catch { return []; } }).sort((a, b) => b.startedAt.localeCompare(a.startedAt)); }
export function readConversationPage(runDirectory: string, offset = 0, limit = 200) { const filePath = assertAppPath(path.join(runDirectory, "conversation.jsonl")); const lines = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8").split(/\r?\n/).filter(Boolean) : []; const safeOffset = Math.max(0, Math.min(lines.length, Math.trunc(offset))); const safeLimit = Math.max(1, Math.min(500, Math.trunc(limit))); return { events: lines.slice(safeOffset, safeOffset + safeLimit).map((line) => JSON.parse(line) as AiAnalysisConversationEvent), offset: safeOffset, nextOffset: Math.min(lines.length, safeOffset + safeLimit), total: lines.length, hasMore: safeOffset + safeLimit < lines.length }; }
export function deleteRunArchive(runDirectory: string) { const safe = assertAppPath(runDirectory); const root = assertAppPath(path.join(getExportsDir(), "ai-analysis", "runs")); const relative = path.relative(root, safe); if (!relative || relative.startsWith("..") || path.isAbsolute(relative)) throw new Error("RUN_ARCHIVE_DELETE_OUTSIDE_ROOT"); fs.rmSync(safe, { recursive: true, force: false }); }