import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { AiAnalysisError, type AiActiveAnalysisResultV0325, type AiAnalysisAttemptV0325, type AiAnalysisRun, type AiNavigationDecisionV0325 } from "../shared/aiAnalysisContract.js";

const sha256 = (value: Buffer | string) => crypto.createHash("sha256").update(value).digest("hex");
const now = () => new Date().toISOString();
function atomicJson(filePath: string, value: unknown) { fs.mkdirSync(path.dirname(filePath), { recursive: true }); const temp = `${filePath}.${process.pid}.${crypto.randomUUID()}.tmp`; const fd = fs.openSync(temp, "wx", 0o600); try { fs.writeFileSync(fd, JSON.stringify(value, null, 2) + "\n", "utf8"); fs.fsyncSync(fd); } finally { fs.closeSync(fd); } fs.renameSync(temp, filePath); const reopened = fs.readFileSync(filePath); if (sha256(reopened) !== sha256(JSON.stringify(value, null, 2) + "\n")) throw new AiAnalysisError("AI_ARTIFACT_HASH_MISMATCH", `Durable reopen hash mismatch: ${path.basename(filePath)}`); }
function appendJsonl(filePath: string, value: unknown) { fs.mkdirSync(path.dirname(filePath), { recursive: true }); const fd = fs.openSync(filePath, "a"); try { fs.writeSync(fd, JSON.stringify(value) + "\n"); fs.fsyncSync(fd); } finally { fs.closeSync(fd); } }
function validSuccessfulRun(run: AiAnalysisRun) { return ["completed", "completed_with_quality_warnings", "completed_with_report_error", "completed_with_persistence_error"].includes(run.status) && run.results.length > 0 && run.results.length === run.selectedDiffIds.length && Boolean(run.analyzedFilePath && run.analyzedFileSha256 && run.completedAt); }
export class AnalysisAttemptStoreV0325 {
  private attemptsValue: AiAnalysisAttemptV0325[] = [];
  constructor(private readonly root: string) { fs.mkdirSync(root, { recursive: true }); }
  get attempts() { return structuredClone(this.attemptsValue); }
  find(analysisAttemptId: string) { return this.attemptsValue.find((item) => item.analysisAttemptId === analysisAttemptId) ?? null; }
  begin(input: { pendingDatasetSha256: string | null; activeRuleSetId: string | null; instructionMode: string; effectiveInstructionSha256?: string | null }) { const created = new Date(); const analysisAttemptId = `attempt_${crypto.randomUUID()}`; const archivePath = path.join(this.root, analysisAttemptId); const attempt: AiAnalysisAttemptV0325 = { schemaVersion: "jaa-analysis-attempt-v1", analysisAttemptId, requestedAtUtc: created.toISOString(), requestedAtLocal: created.toLocaleString("sv-SE"), pendingDatasetSha256: input.pendingDatasetSha256, activeRuleSetId: input.activeRuleSetId, instructionMode: input.instructionMode, effectiveInstructionSha256: input.effectiveInstructionSha256 ?? null, preflightFindings: [], dispatchDecision: "PENDING", linkedRunId: null, navigationDecisions: [], terminalStatus: "PREFLIGHT", archivePath }; fs.mkdirSync(archivePath, { recursive: false }); this.attemptsValue.unshift(attempt); this.persist(attempt); return attempt; }
  preflightFailed(attempt: AiAnalysisAttemptV0325, errorCode: string, message: string) { attempt.preflightFindings.push({ errorCode, message }); attempt.dispatchDecision = "DENY"; attempt.terminalStatus = "PREFLIGHT_FAILED"; this.persist(attempt); return attempt; }
  linkRun(attempt: AiAnalysisAttemptV0325, runId: string) { attempt.linkedRunId = runId; attempt.dispatchDecision = "ALLOW"; attempt.terminalStatus = "DISPATCHED"; this.persist(attempt); return attempt; }
  finish(attempt: AiAnalysisAttemptV0325, status: "COMPLETED" | "FAILED") { attempt.terminalStatus = status; this.persist(attempt); }
  navigation(attempt: AiAnalysisAttemptV0325, input: Omit<AiNavigationDecisionV0325, "schemaVersion" | "analysisAttemptId" | "evaluatedAtUtc" | "receiptPath">) { const receipt: AiNavigationDecisionV0325 = { schemaVersion: "jaa-analysis-navigation-decision-v1", analysisAttemptId: attempt.analysisAttemptId, evaluatedAtUtc: now(), ...input }; const receiptPath = path.join(attempt.archivePath, "navigation-decisions.jsonl"); receipt.receiptPath = receiptPath; attempt.navigationDecisions.push(receipt); appendJsonl(receiptPath, receipt); this.persist(attempt); return receipt; }
  private persist(attempt: AiAnalysisAttemptV0325) { atomicJson(path.join(attempt.archivePath, "attempt-manifest.json"), attempt); }
}
export class ActiveResultRegistryV0325 {
  private registry: AiActiveAnalysisResultV0325[] = []; private activeValue: AiActiveAnalysisResultV0325 | null = null; private readonly registryPath: string; private readonly auditPath: string;
  constructor(private readonly root: string) { fs.mkdirSync(root, { recursive: true }); this.registryPath = path.join(root, "successful-result-registry.json"); this.auditPath = path.join(root, "active-result-transactions.jsonl"); this.load(); }
  get active() { return this.activeValue ? structuredClone(this.activeValue) : null; }
  get successful() { return structuredClone([...this.registry].sort((a, b) => b.authoritativeCompletedAtUtc.localeCompare(a.authoritativeCompletedAtUtc))); }
  private load() { try { const stored = JSON.parse(fs.readFileSync(this.registryPath, "utf8")) as { activeResultId?: string; results?: AiActiveAnalysisResultV0325[] }; this.registry = (stored.results ?? []).filter((item) => { try { const bytes = fs.readFileSync(item.analyzedResultPath); return bytes.length === item.analyzedResultBytes && sha256(bytes) === item.analyzedResultSha256 && item.recordCount > 0; } catch { return false; } }); this.activeValue = this.registry.find((item) => item.activeResultId === stored.activeResultId) ?? this.registry.sort((a, b) => b.authoritativeCompletedAtUtc.localeCompare(a.authoritativeCompletedAtUtc))[0] ?? null; } catch { this.registry = []; this.activeValue = null; } }
  activateRun(run: AiAnalysisRun, sourceKind: "ANALYSIS_RUN" | "MANUAL_IMPORT", importId: string | null = null) { if (!validSuccessfulRun(run)) throw new AiAnalysisError("ANALYSIS_INPUT_INVALID", "只有 durable、非空且 count/identity 完整的成功 Analyzed Result 可以成為 Active Dataset。"); const filePath = fs.realpathSync.native(path.resolve(run.analyzedFilePath!)); const bytes = fs.readFileSync(filePath); const hash = sha256(bytes); if (hash !== run.analyzedFileSha256) throw new AiAnalysisError("AI_ARTIFACT_HASH_MISMATCH", "Analyzed Result reopen SHA-256 與 receipt 不符。"); const existing = this.registry.find((item) => item.analyzedResultSha256 === hash); const completedAt = run.completedAt!; const result: AiActiveAnalysisResultV0325 = existing ? { ...existing, activatedAtUtc: now() } : { schemaVersion: "jaa-active-analysis-result-v1", activeResultId: `active_${hash.slice(0, 24)}`, sourceKind, analyzedResultPath: filePath, analyzedResultSha256: hash, analyzedResultBytes: bytes.length, recordCount: run.results.length, sourceDatasetSha256: run.sourceFileSha256, ruleSetId: run.rules.ruleSetId, runId: sourceKind === "ANALYSIS_RUN" ? run.runId : null, importId: sourceKind === "MANUAL_IMPORT" ? importId ?? `import_${crypto.randomUUID()}` : null, authoritativeCompletedAtUtc: completedAt, activatedAtUtc: now(), packageState: run.reportDataPackagePath ? "READY" : "NOT_STARTED", htmlState: run.reportFilePath ? "READY" : "NOT_STARTED", sqliteState: run.databaseCommitReceiptPath ? "COMMITTED" : run.databaseCommitFailurePath ? "FAILED" : sourceKind === "MANUAL_IMPORT" ? "NOT_ALLOWED" : "NOT_STARTED", reportDataPackagePath: run.reportDataPackagePath ?? null, reportDataPackageSha256: run.reportDataPackageSha256 ?? null, htmlPath: run.reportFilePath ?? null, htmlSha256: run.reportFileSha256 ?? null, validationState: run.validationGate?.passed ? "PASSED" : "PASSED_BY_ANALYZED_CONTRACT", qualityState: run.qualityGate?.status ?? "NOT_AVAILABLE", statistics: this.statistics(run.reportDataPackagePath ?? null) }; if (existing) this.registry.splice(this.registry.indexOf(existing), 1); this.registry.push(result); this.activeValue = result; this.persist(); appendJsonl(this.auditPath, { schemaVersion: "jaa-active-result-transaction-receipt-v1", decision: "COMMIT", sourceKind, activeResultId: result.activeResultId, analyzedResultSha256: hash, runId: run.runId, importId: result.importId, activatedAtUtc: result.activatedAtUtc }); return structuredClone(result); }
  activateExisting(activeResultId: string) { const candidate = this.registry.find((item) => item.activeResultId === activeResultId); if (!candidate) throw new AiAnalysisError("ANALYSIS_INPUT_INVALID", "成功結果 registry 中找不到指定 Active Result。"); const bytes = fs.readFileSync(candidate.analyzedResultPath); if (bytes.length !== candidate.analyzedResultBytes || sha256(bytes) !== candidate.analyzedResultSha256) throw new AiAnalysisError("AI_ARTIFACT_HASH_MISMATCH", "歷史 Analyzed Result 已變更，拒絕切換。"); candidate.activatedAtUtc = now(); this.activeValue = candidate; this.persist(); appendJsonl(this.auditPath, { schemaVersion: "jaa-active-result-transaction-receipt-v1", decision: "COMMIT_EXISTING", activeResultId, activatedAtUtc: candidate.activatedAtUtc }); return structuredClone(candidate); }
  refreshDownstream(run: AiAnalysisRun) { if (!this.activeValue || this.activeValue.runId !== run.runId && this.activeValue.analyzedResultSha256 !== run.analyzedFileSha256) return; this.activeValue.packageState = run.reportDataPackagePath ? "READY" : run.reportPackageMode === "DIAGNOSTIC_NON_CANONICAL" ? "FAILED" : "NOT_STARTED"; this.activeValue.htmlState = run.reportFilePath ? "READY" : run.htmlRenderStatus === "failed" ? "FAILED" : "NOT_STARTED"; this.activeValue.sqliteState = run.databaseCommitReceiptPath ? "COMMITTED" : run.databaseCommitFailurePath ? "FAILED" : this.activeValue.sourceKind === "MANUAL_IMPORT" ? "NOT_ALLOWED" : "NOT_STARTED"; this.activeValue.reportDataPackagePath = run.reportDataPackagePath ?? null; this.activeValue.reportDataPackageSha256 = run.reportDataPackageSha256 ?? null; this.activeValue.htmlPath = run.reportFilePath ?? null; this.activeValue.htmlSha256 = run.reportFileSha256 ?? null; this.activeValue.statistics = this.statistics(run.reportDataPackagePath ?? null); this.persist(); }
  private statistics(packagePath: string | null): AiActiveAnalysisResultV0325["statistics"] { if (!packagePath) return { source: "REPORT_DATA_PACKAGE", calculatedAtUtc: null, packageId: null, eventCount: null, uniqueIssueCount: null, skillFindingCount: null, validationFindingCount: null }; try { const data = JSON.parse(fs.readFileSync(packagePath, "utf8")); return { source: "REPORT_DATA_PACKAGE", calculatedAtUtc: now(), packageId: data.packageId ?? null, eventCount: Number(data.baseCounts?.activityEventCount ?? data.records?.length ?? 0), uniqueIssueCount: Number(data.baseCounts?.uniqueIssueCount ?? data.issueSnapshots?.length ?? 0), skillFindingCount: Number(data.baseCounts?.skillFindingCount ?? 0), validationFindingCount: Number(data.baseCounts?.validationFindingCount ?? data.validationFindings?.length ?? 0) }; } catch { return { source: "REPORT_DATA_PACKAGE", calculatedAtUtc: null, packageId: null, eventCount: null, uniqueIssueCount: null, skillFindingCount: null, validationFindingCount: null }; } }
  private persist() { atomicJson(this.registryPath, { schemaVersion: "jaa-successful-analysis-result-registry-v1", activeResultId: this.activeValue?.activeResultId ?? null, results: this.registry }); }
}
export function navigationDecisionV0325(input: { attempt: AiAnalysisAttemptV0325; run: AiAnalysisRun | null; active: AiActiveAnalysisResultV0325 | null }) { const matches = Boolean(input.run && input.active && input.active.runId === input.run.runId && input.run.analyzedFilePath && input.run.analyzedFileSha256 === input.active.analyzedResultSha256); return { runId: input.run?.runId ?? null, fromRoute: "/ai-analysis#workspace", requestedTargetRoute: "/ai-analysis#results", decision: matches ? "ALLOW" as const : input.run ? "DEFER" as const : "DENY" as const, reasonCode: matches ? "ACTIVE_ANALYZED_RESULT_COMMITTED" : input.run ? "ACTIVE_RESULT_NOT_COMMITTED" : "RUN_NOT_CREATED", analyzedResultReceiptId: matches ? input.active!.analyzedResultSha256 : null, activeResultId: matches ? input.active!.activeResultId : null };
}