import crypto from "node:crypto";
import { AiAnalysisError, emptyTokenUsage, type AiDiffAnalysisResult, type AiRulesSnapshot } from "../shared/aiAnalysisContract.js";
import type { CompactPayload } from "./aiAnalysisSingleRunV0311.js";
import type { AiDecisionV0324 } from "./aiAnalysisDecisionContractV0324.js";

export const CANONICAL_RESULT_CONTRACT_VERSION_V0324 = "jaa-canonical-analysis-result-v5" as const;
const sha256 = (value: string) => crypto.createHash("sha256").update(value, "utf8").digest("hex");
export function issueSnapshotIdentityV0324(jiraServerIdentity: string, issueKey: string) { const normalizedIssueKey = issueKey.trim().toUpperCase(); return { snapshotId: `snapshot_${sha256(`${jiraServerIdentity}:${normalizedIssueKey}`).slice(0, 24)}`, jiraServerIdentity, normalizedIssueKey }; }
export function assembleCanonicalResultsV0324(input: { runId: string; compact: CompactPayload; decisions: AiDecisionV0324[]; rules: AiRulesSnapshot; analyzerVersion: string; jiraServerIdentity: string; requestTraceId: string | null; usage?: ReturnType<typeof emptyTokenUsage>; snapshotReferences?: Map<string, { snapshotId: string; snapshotSha256: string; jiraServerIdentity: string; normalizedIssueKey: string }> }): AiDiffAnalysisResult[] {
  const catalog = new Map(input.rules.catalog.map((skill) => [skill.id, skill]));
  return input.decisions.map((decision, index) => {
    const source = input.compact.records[index]; if (!source || decision.recordIndex !== index) throw new AiAnalysisError("AI_DECISION_INDEX_MISSING", `Cannot assemble Decision recordIndex ${decision.recordIndex}; expected ${index}.`);
    const candidates = decision.skillFindings.map((finding) => { const skill = catalog.get(finding.skillId); if (!skill) throw new AiAnalysisError("AI_DECISION_SKILL_ID_INVALID", finding.skillId); return { skillId: finding.skillId, skillName: skill.name, group: skill.group, score: Math.round(finding.confidence * 100), confidence: finding.confidence, confidenceLabel: finding.confidence >= .9 ? "High" as const : finding.confidence >= .6 ? "Medium" as const : "Low" as const, confidenceReason: finding.rationale, positiveSignals: finding.evidenceQuotes.map((quote) => quote.quote), positiveEvidenceRefs: finding.evidenceQuotes.map((quote) => quote.evidenceRef), negativeChecks: finding.negativeChecks.map((detail, checkIndex) => ({ ruleId: `AI_SKILL_CHECK_${checkIndex + 1}`, passed: false, detail, evidenceRefs: finding.evidenceQuotes.map((quote) => quote.evidenceRef) })), negativeEvidenceRefs: [], rejectedNearSkills: [], evidenceQuote: finding.evidenceQuotes[0]?.quote ?? "", evidenceQuotes: finding.evidenceQuotes, evidenceExplanation: finding.evidenceExplanation, skillRationale: finding.rationale, matchedRuleIds: [], reason: finding.rationale, status: "PENDING_REVIEW" as const, candidateStatus: (decision.status === "CLASSIFIED" ? "MATCHED" : decision.status === "FAILED" ? "NEEDS_REVIEW" : decision.status) as "MATCHED" | "EXCLUDED" | "CATALOG_DETAIL_MISSING" | "NEEDS_REVIEW", statusReason: finding.rationale, catalogDetailAvailable: decision.status !== "CATALOG_DETAIL_MISSING" }; });
    const normalizedIssueKey = source.issueKey.trim().toUpperCase(); const snapshotReference = input.snapshotReferences?.get(normalizedIssueKey) ?? { ...issueSnapshotIdentityV0324(input.jiraServerIdentity, source.issueKey), snapshotSha256: sha256(`SOURCE_UNAVAILABLE:${input.jiraServerIdentity}:${normalizedIssueKey}`) };
    return { resultId: `result_${sha256(`${input.runId}:${source.sourceRecordStableId}:${source.sourceContentHash}:${input.rules.snapshotId ?? input.rules.ruleSetId}`).slice(0, 24)}`, sourceDiffId: source.sourceRecordStableId, sourceContentHash: source.sourceContentHash, sourceEvidenceSnapshot: { issueKey: source.issueKey, actor: source.actor, eventTimestamp: source.eventTimestamp, fieldName: source.fieldName, sourceProvenance: source.sourceProvenance, addedText: [...source.addedText], removedText: [...source.removedText] }, evidenceRefs: [...new Set(decision.skillFindings.flatMap((finding) => finding.evidenceQuotes.map((quote) => quote.evidenceRef)))], recordIndex: index, sourceRecordStableId: source.sourceRecordStableId, activityEventId: source.activityEventId, evidenceId: source.evidenceId, decisionConfidence: decision.confidence, decisionRationale: decision.rationale, recordNegativeChecks: decision.recordNegativeChecks, derivedSkillIds: decision.skillFindings.map((finding) => finding.skillId), issueSnapshotReference: snapshotReference, classificationStatus: decision.status === "CLASSIFIED" ? "MATCHED" : decision.status === "FAILED" ? "NEEDS_REVIEW" : decision.status, reviewStatus: "PENDING_REVIEW", reviewAttention: ["CATALOG_DETAIL_MISSING", "NEEDS_REVIEW", "FAILED"].includes(decision.status) ? "NEEDS_REVIEW" : "STANDARD_REVIEW", dispositionReason: decision.rationale, exclusionReason: decision.status === "EXCLUDED" ? decision.rationale : null, unknownReason: decision.status === "UNKNOWN" ? decision.unknownReasons.join("; ") : null, reviewReason: ["NEEDS_REVIEW", "FAILED"].includes(decision.status) ? decision.rationale : null, matchedRuleIds: [], negativeChecks: decision.recordNegativeChecks.map((detail, checkIndex) => ({ ruleId: `AI_RECORD_CHECK_${checkIndex + 1}`, passed: false, detail, evidenceRefs: [source.evidenceId] })), candidates, status: decision.status === "UNKNOWN" ? "UNKNOWN" : decision.status === "EXCLUDED" ? "EXCLUDED" : ["NEEDS_REVIEW", "FAILED"].includes(decision.status) ? "NEEDS_REVIEW" : "PENDING_REVIEW", analyzerVersion: input.analyzerVersion, requestTraceId: input.requestTraceId, usage: input.usage ?? emptyTokenUsage("actual"), rawResultAvailable: true, reviewNote: "", reviewedAt: null };
  });
}