import crypto from "node:crypto";
import type { DecisionValidationV0324,ValidationFindingV0324 } from "./aiAnalysisDecisionContractV0324.js";
import type { DecisionV0326 } from "./aiAnalysisDecisionContractV0326.js";
import type { EvidenceQuoteCatalog,EvidenceQuoteCatalogEntry } from "./evidenceQuoteCatalogV0326.js";
export const QUALITY_CONTRACT_VERSION_V0332="jaa-ai-analysis-quality-v3" as const;
export const MULTI_SKILL_INDEPENDENCE_VERSION_V0332="jaa-multi-skill-quote-independence-v1" as const;
type F=ValidationFindingV0324&{primaryEvidenceQuoteIds?:string[];primaryQuoteKeys?:string[];sharedPrimaryQuoteKeys?:string[];exclusivePrimaryQuoteKeys?:string[];skeletonFingerprintHash?:string;duplicateGroupId?:string;duplicateOccurrenceCount?:number};
export type QualityReportV0332={contractVersion:typeof QUALITY_CONTRACT_VERSION_V0332;multiSkillIndependenceVersion:typeof MULTI_SKILL_INDEPENDENCE_VERSION_V0332;status:"PASSED"|"WARNING"|"BLOCKED";warnings:string[];blockers:string[];metrics:Record<string,number>;findings:F[]};
const hash=(v:string)=>crypto.createHash("sha256").update(v).digest("hex"),norm=(v:string)=>v.trim().toLocaleLowerCase("zh-TW"),ratio=(a:string[])=>{const p=a.map(norm).filter(Boolean);return p.length?(p.length-new Set(p).size)/p.length:0},boiler=/(same as above|依規則處理|請參考前述|一般性修改|generic evidence|placeholder|todo|\bn\/?a\b)/i;
export const quoteIdentityKeyV0332=(q:EvidenceQuoteCatalogEntry)=>[q.sourceRecordStableId,q.sourceJsonPointer,q.rawStartOffset,q.rawEndOffset,q.quoteSha256].join("\u001f");
export function evaluateDecisionQualityV0332(i:{decisions:DecisionV0326[];quoteCatalog:EvidenceQuoteCatalog;legacyValidation?:DecisionValidationV0324}):QualityReportV0332{
 const out:F[]=[],qm=new Map(i.quoteCatalog.entries.map(q=>[q.evidenceQuoteId,q]));let multi=0,blocked=0,missingSkills=0;const texts:Array<{p:string;v:string;r:number;s:string|null;id:string|null}>=[];
 for(const d of i.decisions){const stable=i.quoteCatalog.entries.find(q=>q.recordIndex===d.recordIndex)?.sourceRecordStableId??null;texts.push({p:`/records/${d.recordIndex}/rationale`,v:d.rationale,r:d.recordIndex,s:stable,id:null});d.skillFindings.forEach((f,n)=>{texts.push({p:`/records/${d.recordIndex}/skillFindings/${n}/evidenceExplanation`,v:f.evidenceExplanation,r:d.recordIndex,s:stable,id:f.skillId},{p:`/records/${d.recordIndex}/skillFindings/${n}/rationale`,v:f.rationale,r:d.recordIndex,s:stable,id:f.skillId});f.negativeChecks.forEach((v,x)=>texts.push({p:`/records/${d.recordIndex}/skillFindings/${n}/negativeChecks/${x}`,v,r:d.recordIndex,s:stable,id:f.skillId}))});if(d.skillFindings.length<2)continue;multi++;const by=new Map<number,string[]>(),owners=new Map<string,Set<number>>();d.skillFindings.forEach((f,n)=>{const keys=[...new Set(f.evidenceQuoteIds.map(x=>qm.get(x)).filter((q):q is EvidenceQuoteCatalogEntry=>Boolean(q&&q.recordIndex===d.recordIndex&&q.evidenceRoleEligibility.includes("PRIMARY_CHANGE"))).map(quoteIdentityKeyV0332))];by.set(n,keys);keys.forEach(k=>owners.set(k,new Set([...(owners.get(k)??[]),n])))});let row=false;d.skillFindings.forEach((f,n)=>{const keys=by.get(n)??[],shared=keys.filter(k=>(owners.get(k)?.size??0)>1),exclusive=keys.filter(k=>(owners.get(k)?.size??0)===1);if(exclusive.length)return;row=true;missingSkills++;out.push({code:"MULTI_SKILL_EXCLUSIVE_PRIMARY_QUOTE_MISSING",severity:"ERROR",stage:"QUALITY_GATE",recordIndex:d.recordIndex,sourceRecordStableId:stable,skillId:f.skillId,evidenceSegmentId:null,jsonPointer:`/records/${d.recordIndex}/skillFindings/${n}/evidenceQuoteIds`,expected:"at least one exclusive PRIMARY_CHANGE QuoteIdentityKey",observed:keys.length?"all PRIMARY_CHANGE QuoteIdentityKeys are shared by another Skill":"no valid PRIMARY_CHANGE QuoteIdentityKey",message:"此 Skill 缺少未被同筆其他 Skill 共用的 PRIMARY_CHANGE Quote。",primaryEvidenceQuoteIds:f.evidenceQuoteIds.filter(x=>Boolean(qm.get(x)?.evidenceRoleEligibility.includes("PRIMARY_CHANGE"))),primaryQuoteKeys:keys,sharedPrimaryQuoteKeys:shared,exclusivePrimaryQuoteKeys:exclusive})});if(row)blocked++}
 for(const t of texts)if(boiler.test(t.v)){const h=hash(norm(t.v));out.push({code:"BOILERPLATE_EVIDENCE_PATTERN",severity:"WARNING",stage:"QUALITY_GATE",recordIndex:t.r,sourceRecordStableId:t.s,skillId:t.id,evidenceSegmentId:null,jsonPointer:t.p,expected:"record-specific model-authored prose",observed:t.v.slice(0,180),message:"偵測到樣板式模型說明。",skeletonFingerprintHash:h,duplicateGroupId:`boilerplate_${h.slice(0,20)}`,duplicateOccurrenceCount:1})}
 const unique=[...new Map(out.map(f=>[`${f.code}:${f.jsonPointer}`,f])).values()],errors=[...(i.legacyValidation?.findings.filter(f=>f.severity==="ERROR").map(f=>f.code)??[]),...unique.filter(f=>f.severity==="ERROR").map(f=>f.code)],warnings=[...new Set(unique.filter(f=>f.severity==="WARNING").map(f=>f.code))],exp=i.decisions.flatMap(d=>d.skillFindings.map(f=>f.evidenceExplanation)),rat=i.decisions.flatMap(d=>d.skillFindings.map(f=>f.rationale)),unk=i.decisions.flatMap(d=>d.unknownReasons);
 return {contractVersion:QUALITY_CONTRACT_VERSION_V0332,multiSkillIndependenceVersion:MULTI_SKILL_INDEPENDENCE_VERSION_V0332,status:errors.length?"BLOCKED":warnings.length?"WARNING":"PASSED",warnings,blockers:[...new Set(errors)],metrics:{evidenceExplanationExactDuplicateRatio:ratio(exp),skillRationaleExactDuplicateRatio:ratio(rat),unknownReasonExactDuplicateRatio:ratio(unk),multiSkillRecordCount:multi,multiSkillMissingIndependentFindingCount:blocked,multiSkillMissingExclusiveSkillCount:missingSkills,boilerplateEvidencePatternCount:unique.filter(f=>f.code==="BOILERPLATE_EVIDENCE_PATTERN").length},findings:unique};
}