import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

export const ARTIFACT_TOKEN_CONTRACT = "jaa-artifact-submission-token-v1" as const;
export const ARTIFACT_IDENTITY_RECEIPT_CONTRACT = "jaa-artifact-identity-receipt-v1" as const;
export type ArtifactIdentityErrorCode = "AI_ARTIFACT_TOKEN_MISSING" | "AI_ARTIFACT_TOKEN_INVALID" | "AI_ARTIFACT_TOKEN_EXPIRED" | "AI_ARTIFACT_TOKEN_REPLAYED" | "AI_ARTIFACT_TOKEN_SCOPE_MISMATCH" | "AI_ARTIFACT_IDENTITY_INTERNAL_MISMATCH" | "AI_ARTIFACT_SUBMISSION_DUPLICATE";
export type ApprovedArtifactIdentity = Readonly<{ identityVersion: "jaa-approved-artifact-identity-v1"; analysisAttemptId: string; runId: string; requestId: string; threadId: string; turnId: string; provider: string; model: string; sourceDatasetSha256: string; sourceDatasetBytes: number; sourceRecordCount: number; rulesSnapshotId: string; manifestSha256: string; commonRulesSha256: string; catalogSha256: string; decisionContract: "jaa-ai-analysis-decisions-v5"; outputSchemaSha256: string; promptIdentity: "JAA-CHATGPT-ZH-TW-0.3.26"; bridgeIdentity: "0.3.26-bridge-v8"; createdAtUtc: string }>;
export type ArtifactSubmissionV0326 = { artifactSubmissionToken: string; decisions: unknown; analysisReportMarkdown: string; finalSummaryZhTw: string };
type TokenRecord = { tokenHash: string; tokenPrefix: string; dynamicToolName: string; identityHash: string; runId: string; analysisAttemptId: string; threadId: string; turnId: string; expiresAtMs: number; consumedAtUtc: string | null };
const sha256 = (value: string | Buffer) => crypto.createHash("sha256").update(value).digest("hex");
const stable = (value: unknown): unknown => Array.isArray(value) ? value.map(stable) : value && typeof value === "object" ? Object.fromEntries(Object.keys(value as Record<string, unknown>).sort().map((key) => [key, stable((value as Record<string, unknown>)[key])])) : value;
const stableJson = (value: unknown) => JSON.stringify(stable(value));
function durableJson(target: string, value: unknown) { fs.mkdirSync(path.dirname(target), { recursive: true }); const text = JSON.stringify(value, null, 2) + "\n"; const temp = `${target}.${process.pid}.${crypto.randomUUID()}.tmp`; const fd = fs.openSync(temp, "wx", 0o600); try { fs.writeFileSync(fd, text, "utf8"); fs.fsyncSync(fd); } finally { fs.closeSync(fd); } fs.renameSync(temp, target); const reopened = fs.readFileSync(target); if (sha256(reopened) !== sha256(Buffer.from(text))) throw new Error("AI_ARTIFACT_HASH_MISMATCH:durable reopen hash mismatch"); return { filePath: target, bytes: reopened.length, sha256: sha256(reopened) }; }
export function createApprovedArtifactIdentity(input: Omit<ApprovedArtifactIdentity, "identityVersion" | "decisionContract" | "promptIdentity" | "bridgeIdentity" | "createdAtUtc"> & { createdAtUtc?: string }): ApprovedArtifactIdentity { const identity = { identityVersion: "jaa-approved-artifact-identity-v1", ...input, decisionContract: "jaa-ai-analysis-decisions-v5", promptIdentity: "JAA-CHATGPT-ZH-TW-0.3.26", bridgeIdentity: "0.3.26-bridge-v8", createdAtUtc: input.createdAtUtc ?? new Date().toISOString() } as const; return Object.freeze(identity); }
export function artifactIdentityHash(identity: ApprovedArtifactIdentity) { return sha256(stableJson(identity)); }
export class ArtifactSubmissionTokenService {
  private readonly records = new Map<string, TokenRecord>();
  issue(identity: ApprovedArtifactIdentity, dynamicToolName: string, ttlMs = 30 * 60_000) { const token = crypto.randomBytes(32).toString("base64url"); const tokenHash = sha256(token); const record: TokenRecord = { tokenHash, tokenPrefix: token.slice(0, 8), dynamicToolName, identityHash: artifactIdentityHash(identity), runId: identity.runId, analysisAttemptId: identity.analysisAttemptId, threadId: identity.threadId, turnId: identity.turnId, expiresAtMs: Date.now() + ttlMs, consumedAtUtc: null }; this.records.set(tokenHash, record); return { token, receipt: { schemaVersion: ARTIFACT_TOKEN_CONTRACT, tokenHash, tokenPrefix: record.tokenPrefix, identityHash: record.identityHash, dynamicToolName, runId: record.runId, analysisAttemptId: record.analysisAttemptId, threadId: record.threadId, turnId: record.turnId, expiresAtUtc: new Date(record.expiresAtMs).toISOString(), fullTokenPersisted: false } }; }
  consume(token: unknown, identity: ApprovedArtifactIdentity, context: { runId: string; threadId: string; turnId: string; dynamicToolName: string }, nowMs = Date.now()) { const fail = (code: ArtifactIdentityErrorCode, message: string): never => { throw Object.assign(new Error(`${code}:${message}`), { code }); }; const tokenValue = typeof token === "string" ? token : ""; if (!tokenValue) fail("AI_ARTIFACT_TOKEN_MISSING", "Artifact submission token is required."); const tokenHash = sha256(tokenValue); const found = this.records.get(tokenHash); if (!found) fail("AI_ARTIFACT_TOKEN_INVALID", "Artifact submission token is unknown."); const record = found!; if (record.consumedAtUtc) fail("AI_ARTIFACT_TOKEN_REPLAYED", "Artifact submission token was already consumed."); if (nowMs > record.expiresAtMs) fail("AI_ARTIFACT_TOKEN_EXPIRED", "Artifact submission token expired."); const scopeMatches = record.identityHash === artifactIdentityHash(identity) && record.runId === context.runId && record.threadId === context.threadId && record.turnId === context.turnId && record.dynamicToolName === context.dynamicToolName; if (!scopeMatches) fail("AI_ARTIFACT_TOKEN_SCOPE_MISMATCH", "Artifact submission token scope does not match this Run/Thread/Turn/tool."); record.consumedAtUtc = new Date(nowMs).toISOString(); return { schemaVersion: ARTIFACT_IDENTITY_RECEIPT_CONTRACT, accepted: true, tokenBindingResult: "MATCH", tokenHash, tokenPrefix: record.tokenPrefix, identityHash: record.identityHash, consumedAtUtc: record.consumedAtUtc };
  }
}
export function buildIdentityReceipt(identity: ApprovedArtifactIdentity, actual: ApprovedArtifactIdentity, tokenBindingResult: string) { const fields = Object.keys(identity) as Array<keyof ApprovedArtifactIdentity>; const comparisons = fields.map((field) => { const expected = identity[field]; const observed = actual[field]; const expectedNormalized = typeof expected === "string" ? expected.normalize("NFC") : expected; const observedNormalized = typeof observed === "string" ? observed.normalize("NFC") : observed; return { field, expectedSource: "ApprovedArtifactIdentity", actualSource: "Bridge local injection", expectedType: typeof expected, actualType: typeof observed, expectedNormalized, actualNormalized: observedNormalized, matched: typeof expected === typeof observed && expectedNormalized === observedNormalized }; }); const mismatch = comparisons.find((item) => !item.matched); return { schemaVersion: ARTIFACT_IDENTITY_RECEIPT_CONTRACT, tokenBindingResult, comparisons, accepted: !mismatch, firstMismatchCode: mismatch ? "AI_ARTIFACT_IDENTITY_INTERNAL_MISMATCH" : null, createdAtUtc: new Date().toISOString() }; }
export function persistAiSubmittedArtifact(runDirectory: string, attemptNumber: number, submission: ArtifactSubmissionV0326, identity: ApprovedArtifactIdentity) { const directory = path.join(runDirectory, "artifact-attempts"); const label = String(attemptNumber).padStart(3, "0"); const target = path.join(directory, `ai-submitted-artifact-attempt-${label}.json`); if (fs.existsSync(target)) throw Object.assign(new Error("AI_ARTIFACT_SUBMISSION_DUPLICATE:attempt already exists"), { code: "AI_ARTIFACT_SUBMISSION_DUPLICATE" }); const safeSubmission = { schemaVersion: "jaa-ai-submitted-artifact-v1", state: "AI_SUBMITTED", receivedAtUtc: new Date().toISOString(), artifactSubmissionToken: "[masked]", artifactSubmissionTokenHash: sha256(submission.artifactSubmissionToken), approvedArtifactIdentity: identity, decisions: submission.decisions, analysisReportMarkdown: submission.analysisReportMarkdown, finalSummaryZhTw: submission.finalSummaryZhTw }; const persisted = durableJson(target, safeSubmission); const receipt = durableJson(path.join(directory, `ai-submitted-artifact-attempt-${label}.receipt.json`), { schemaVersion: "jaa-ai-submitted-artifact-receipt-v1", ...persisted, state: "AI_SUBMITTED", reopenHashVerified: true, createdAtUtc: new Date().toISOString() }); return { artifact: persisted, receipt, safeSubmission };
}
export function tokenLeakFree(value: unknown, token: string) { return !JSON.stringify(value).includes(token); }