import crypto from "node:crypto";
import type { EvidenceSegmentV0324 } from "./aiAnalysisEvidenceSegmenterV0324.js";

export const EVIDENCE_QUOTE_CATALOG_VERSION = "JAA-EVIDENCE-QUOTE-CATALOG-1.0.0" as const;
export type EvidenceQuoteCatalogEntry = { evidenceQuoteId: string; recordIndex: number; sourceRecordStableId: string; evidenceRef: string; containerEvidenceSegmentId: string; quoteOrdinal: number; sourceJsonPointer: string; containerStartOffset: number; containerEndOffset: number; rawStartOffset: number; rawEndOffset: number; exactSourceSubstring: string; displayText: string; evidenceRoleEligibility: Array<"PRIMARY_CHANGE" | "SUPPORTING_CONTEXT">; normalizationOperations: string[]; sourceContentHash: string; quoteSha256: string; catalogVersion: typeof EVIDENCE_QUOTE_CATALOG_VERSION };
export type EvidenceQuoteCatalog = { schemaVersion: "jaa-evidence-quote-catalog-v1"; catalogVersion: typeof EVIDENCE_QUOTE_CATALOG_VERSION; recordCount: number; quoteCount: number; entries: EvidenceQuoteCatalogEntry[]; catalogSha256: string };
const sha256 = (value: string) => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const stable = (value: unknown): unknown => Array.isArray(value) ? value.map(stable) : value && typeof value === "object" ? Object.fromEntries(Object.keys(value as Record<string, unknown>).sort().map((key) => [key, stable((value as Record<string, unknown>)[key])])) : value;
function decodedDisplay(raw: string) { const operations: string[] = []; let display = raw; const trimmed = raw.trim(); if (trimmed !== raw) operations.push("trim-display-only"); try { if (trimmed.startsWith('"') && trimmed.endsWith('"')) { display = JSON.parse(trimmed); operations.push("json-string-unescape-display-only"); } else if (trimmed.startsWith("{") || trimmed.startsWith("[")) { const value = JSON.parse(trimmed); if (typeof value === "string") display = value; else if (value && typeof value === "object" && !Array.isArray(value)) { const entries = Object.entries(value as Record<string, unknown>); if (entries.length === 1 && typeof entries[0][1] === "string") { display = entries[0][1]; operations.push("single-json-wrapper-unwrapped-display-only"); } } } } catch { display = raw; } display = String(display).replace(/\\r\\n/g, "\r\n").replace(/\\n/g, "\n").replace(/\\t/g, "\t"); if (display !== raw && !operations.length) operations.push("literal-escape-display-only"); return { display, operations }; }
function ranges(raw: string, display: string) { const lines = display.split(/\r\n|\n|\r/); if (lines.length <= 1) return [{ rawStart: 0, rawEnd: raw.length, exact: raw, display }]; const result: Array<{ rawStart: number; rawEnd: number; exact: string; display: string }> = []; let cursor = 0; for (const line of lines) { if (!line) continue; let start = raw.indexOf(line, cursor); let exact = line; if (start < 0) { const escaped = JSON.stringify(line).slice(1, -1); start = raw.indexOf(escaped, cursor); exact = start >= 0 ? escaped : raw; } if (start < 0) start = 0; const end = start + exact.length; result.push({ rawStart: start, rawEnd: end, exact, display: line }); cursor = end; } return result.length ? result : [{ rawStart: 0, rawEnd: raw.length, exact: raw, display }]; }
export function buildEvidenceQuoteCatalog(segments: EvidenceSegmentV0324[]): EvidenceQuoteCatalog { const entries: EvidenceQuoteCatalogEntry[] = []; for (const segment of [...segments].sort((a,b)=>a.recordIndex-b.recordIndex || a.sourceJsonPointer.localeCompare(b.sourceJsonPointer))) { const decoded = decodedDisplay(segment.exactText); const eligible = segment.evidenceRoleEligibility === "INELIGIBLE" ? [] : [segment.evidenceRoleEligibility]; ranges(segment.exactText, decoded.display).forEach((part, quoteOrdinal) => { const sourceContentHash = sha256(segment.exactText); const quoteSha256 = sha256(part.exact); const identity = [segment.sourceRecordStableId, segment.evidenceSegmentId, part.rawStart, part.rawEnd, quoteSha256].join(":"); entries.push({ evidenceQuoteId: `eq_${sha256(identity).slice(0,32)}`, recordIndex: segment.recordIndex, sourceRecordStableId: segment.sourceRecordStableId, evidenceRef: segment.evidenceRef, containerEvidenceSegmentId: segment.evidenceSegmentId, quoteOrdinal, sourceJsonPointer: segment.sourceJsonPointer, containerStartOffset: 0, containerEndOffset: segment.exactText.length, rawStartOffset: part.rawStart, rawEndOffset: part.rawEnd, exactSourceSubstring: part.exact, displayText: part.display, evidenceRoleEligibility: eligible, normalizationOperations: decoded.operations, sourceContentHash, quoteSha256, catalogVersion: EVIDENCE_QUOTE_CATALOG_VERSION }); }); } const base = { schemaVersion: "jaa-evidence-quote-catalog-v1" as const, catalogVersion: EVIDENCE_QUOTE_CATALOG_VERSION, recordCount: new Set(segments.map((item)=>item.recordIndex)).size, quoteCount: entries.length, entries }; return { ...base, catalogSha256: sha256(JSON.stringify(stable(base))) }; }
export function validateQuoteTrace(entry: EvidenceQuoteCatalogEntry, segment: EvidenceSegmentV0324) { const raw = segment.exactText.slice(entry.rawStartOffset, entry.rawEndOffset); return entry.containerEvidenceSegmentId === segment.evidenceSegmentId && entry.recordIndex === segment.recordIndex && raw === entry.exactSourceSubstring && sha256(raw) === entry.quoteSha256 && sha256(segment.exactText) === entry.sourceContentHash; }
export function quoteCatalogJsonl(catalog: EvidenceQuoteCatalog) { return catalog.entries.map((entry) => JSON.stringify(entry)).join("\n") + (catalog.entries.length ? "\n" : ""); }