const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const { root, artifacts, moduleApi } = require("./v0330-test-helpers.cjs");
const api = moduleApi();
const built = path.join(root, "dist-electron", "jaa-analysis-bridge");
const sourceManifest = JSON.parse(fs.readFileSync(path.join(built, api.BRIDGE_MANIFEST_V0330), "utf8"));
const expected = { expectedBytes: sourceManifest.artifactBytes, expectedSha256: sourceManifest.artifactSha256 };
function fixture(name) { const folder = path.join(artifacts, name); fs.rmSync(folder, { recursive: true, force: true }); fs.mkdirSync(folder, { recursive: true }); fs.cpSync(built, path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY), { recursive: true }); return folder; }
function resolve(folder, extra = {}) { return api.resolveAnalysisBridgeArtifactV0330({ appIsPackaged: true, processResourcesPath: folder, phase: "diagnostic", distributionKind: "win-unpacked", ...expected, ...extra }).receipt; }
assert.equal(resolve(fixture("ready")).status, "ready");
let folder = fixture("manifest-missing"); fs.unlinkSync(path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_MANIFEST_V0330)); assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_MANIFEST_MISSING");
folder = fixture("manifest-invalid"); fs.writeFileSync(path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_MANIFEST_V0330), "not-json"); assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_MANIFEST_INVALID");
folder = fixture("artifact-missing"); fs.unlinkSync(path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_ARTIFACT_V0330)); assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_PACKAGED_ARTIFACT_MISSING");
folder = fixture("artifact-directory"); fs.rmSync(path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_ARTIFACT_V0330)); fs.mkdirSync(path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_ARTIFACT_V0330)); assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_PACKAGED_ARTIFACT_NOT_FILE");
folder = fixture("version-mismatch"); { const file = path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_MANIFEST_V0330); const value = JSON.parse(fs.readFileSync(file)); value.bridgeIdentity = "0.3.29-bridge-v11"; fs.writeFileSync(file, JSON.stringify(value)); } assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_VERSION_MISMATCH");
folder = fixture("bytes-mismatch"); fs.appendFileSync(path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_ARTIFACT_V0330), "x"); assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_SIZE_MISMATCH");
folder = fixture("hash-mismatch"); { const file = path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_ARTIFACT_V0330); const bytes = fs.readFileSync(file); bytes[0] ^= 1; fs.writeFileSync(file, bytes); } assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_SHA256_MISMATCH");
folder = fixture("transport-mismatch"); { const file = path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_MANIFEST_V0330); const value = JSON.parse(fs.readFileSync(file)); value.transport = "bridge-resumable-v2"; fs.writeFileSync(file, JSON.stringify(value)); } assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_CONTRACT_MISMATCH");
folder = fixture("decision-mismatch"); { const file = path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_MANIFEST_V0330); const value = JSON.parse(fs.readFileSync(file)); value.decisionContract = "jaa-ai-analysis-decisions-v4"; fs.writeFileSync(file, JSON.stringify(value)); } assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_CONTRACT_MISMATCH");
folder = fixture("loadability"); { const artifact = path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_ARTIFACT_V0330); fs.writeFileSync(artifact, "this is not javascript"); const bytes = fs.readFileSync(artifact); const hash = crypto.createHash("sha256").update(bytes).digest("hex"); const manifestFile = path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, api.BRIDGE_MANIFEST_V0330); const value = JSON.parse(fs.readFileSync(manifestFile)); value.artifactBytes = bytes.length; value.artifactSha256 = hash; fs.writeFileSync(manifestFile, JSON.stringify(value)); assert.equal(resolve(folder, { expectedBytes: bytes.length, expectedSha256: hash }).rootErrorCode, "AI_BRIDGE_LOADABILITY_FAILED"); }
folder = path.join(artifacts, "no-fallback"); fs.rmSync(folder, { recursive: true, force: true }); fs.mkdirSync(path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY), { recursive: true }); fs.copyFileSync(path.join(built, api.BRIDGE_ARTIFACT_V0330), path.join(folder, "analysis-bridge-v0330.cjs")); fs.copyFileSync(path.join(built, api.BRIDGE_ARTIFACT_V0330), path.join(folder, api.BRIDGE_RESOURCE_DIRECTORY, "analysis-bridge-v0329.cjs")); const originalPath = process.env.PATH; process.env.PATH = folder + path.delimiter + originalPath; try { assert.equal(resolve(folder).rootErrorCode, "AI_BRIDGE_MANIFEST_MISSING"); } finally { process.env.PATH = originalPath; }
const ledgerFile = path.join(artifacts, "dispatch-ledger.jsonl"); fs.rmSync(ledgerFile, { force: true }); const ledger = new api.ProviderDispatchLedgerV0330(ledgerFile); ledger.append("prepared", { idempotencyKey: "p" }); ledger.append("dispatch_attempted", { idempotencyKey: "d" }); ledger.append("dispatch_attempted", { idempotencyKey: "d" }); ledger.append("provider_contacted", { idempotencyKey: "c" }); ledger.append("thread_created", { idempotencyKey: "t" }); ledger.append("turn_start_attempted", { idempotencyKey: "tsa" }); ledger.append("turn_accepted", { idempotencyKey: "ta" }); assert.equal(ledger.projection.providerDispatchAttemptCount, 1); assert.equal(ledger.projection.acceptedTurnCount, 1); assert.equal(fs.readFileSync(ledgerFile, "utf8").trim().split(/\r?\n/).length, 6);
const source = fs.readFileSync(path.join(root, "electron", "aiAnalysisIpc.ts"), "utf8"); assert.match(source, /prepared_message.*, "APP_ONLY"/); assert.match(source, /providerEvent\.type === "turn_started"[\s\S]*CHATGPT_VISIBLE/); assert.equal(/append\("user_message", "CHATGPT_VISIBLE"[\s\S]{0,300}providerPromise/.test(source), false);
execFileSync(process.execPath, [path.join(root, "scripts", "test-v0329.cjs")], { stdio: "inherit" });
console.log("v0.3.30 Bridge resolver, dispatch truth, and v0.3.29 regression tests passed");
